package rules

// attackTacticsRules broadens coverage using ATT&CK tactic-aligned heuristics.
func attackTacticsRules() []Rule { //nolint:funlen // declarative rule table
	return []Rule{
		// Execution (TA0002).
		{
			ID:          "ATK-EXE-001",
			Title:       "Encoded PowerShell execution",
			Description: "Detected encoded PowerShell invocation commonly used to execute staged payloads.",
			Category:    "execution",
			Mitre:       "T1059.001",
			Severity:    SeverityLow,
			Pattern:     `(?i)\bpowershell(?:\.exe)?\b.{0,60}(-enc|-encodedcommand)\b`,
			Target:      TargetContent,
		},
		{
			ID:          "ATK-EXE-002",
			Title:       "Shell command-string execution",
			Description: "Detected shell invocation using command-string execution flags often used in one-shot payload launchers.",
			Category:    "execution",
			Mitre:       "T1059.004",
			Severity:    SeverityLow,
			Pattern:     `(?i)\b(bash|sh|zsh|cmd|powershell)\b.{0,24}\s(-c|/c)\b`,
			Target:      TargetContent,
		},
		{
			ID:          "ATK-EXE-003",
			Title:       "Container/cluster command execution marker",
			Description: "Detected remote command execution patterns through container or Kubernetes administration tools.",
			Category:    "execution",
			Mitre:       "T1609",
			Severity:    SeverityLow,
			Pattern:     `(?i)\b(kubectl\s+exec|docker\s+exec|ctr\s+task\s+exec)\b`,
			Target:      TargetContent,
		},
		{
			ID:          "ATK-EXE-004",
			Title:       "Direct interpreter launch from remote URL",
			Description: "Detected direct invocation of language runtime against remote script content.",
			Category:    "execution",
			Mitre:       "T1059",
			Severity:    SeverityLow,
			Pattern:     `(?i)\b(python|node|ruby|perl)\b.{0,160}https?://`,
			Target:      TargetContent,
		},
		{
			ID:          "ATK-EXE-005",
			Title:       "Managed runtime exploit primitive marker",
			Description: "Detected JNDI/deserialization/in-memory runtime execution markers frequently missed by kernel-only telemetry.",
			Category:    "execution",
			Mitre:       "T1059",
			Severity:    SeverityLow,
			Pattern:     `(?i)(jndi:(ldap|rmi|dns)|ObjectInputStream|readObject\(|java\.lang\.Runtime\.getRuntime\(\)\.exec|ysoserial)`,
			Target:      TargetContent,
		},

		// Persistence (TA0003).
		{
			ID:          "ATK-PER-001",
			Title:       "Cron or systemd persistence path",
			Description: "Detected cron/systemd timer/service path often used for recurring persistence.",
			Category:    "persistence",
			Mitre:       "T1053",
			Severity:    SeverityMedium,
			Pattern:     `(?i)(^|/)(crontab|cron\.(d|daily|hourly)|systemd/.+\.(service|timer))$`,
			Target:      TargetPath,
		},
		{
			ID:          "ATK-PER-002",
			Title:       "SSH authorized_keys persistence modification",
			Description: "Detected commands that append or overwrite SSH authorized_keys entries.",
			Category:    "persistence",
			Mitre:       "T1098.004",
			Severity:    SeverityHigh,
			Pattern:     `(?i)(authorized_keys.{0,40}(>>|>|tee)|echo.{0,120}ssh-(rsa|ed25519).{0,120}authorized_keys)`,
			Target:      TargetContent,
		},
		{
			ID:          "ATK-PER-003",
			Title:       "Shell initialization file persistence",
			Description: "Detected references to shell startup files commonly abused for persistence.",
			Category:    "persistence",
			Mitre:       "T1546.004",
			Severity:    SeverityMedium,
			Pattern:     `(?i)(\.bashrc|\.bash_profile|\.zshrc|/etc/profile|/etc/bash\.bashrc)`,
			Target:      TargetContent,
		},
		{
			ID:          "ATK-PER-004",
			Title:       "Python startup hook persistence marker",
			Description: "Detected Python startup hook files or modules associated with auto-executed persistence.",
			Category:    "persistence",
			Mitre:       "T1546.018",
			Severity:    SeverityHigh,
			Pattern:     `(?i)(sitecustomize\.py|usercustomize\.py|\.pth\b)`,
			Target:      TargetContent,
		},
		{
			ID:          "ATK-PER-005",
			Title:       "Launchd or run-key persistence marker",
			Description: "Detected common launchd plist or Windows Run-key persistence paths.",
			Category:    "persistence",
			Mitre:       "T1547.001",
			Severity:    SeverityMedium,
			Pattern:     `(?i)(launchagents|launchdaemons|hkcu\\software\\microsoft\\windows\\currentversion\\run|hklm\\software\\microsoft\\windows\\currentversion\\run)`,
			Target:      TargetContent,
		},

		// Defense Evasion (TA0005).
		{
			ID:          "ATK-DEF-001",
			Title:       "Log/history clearing command",
			Description: "Detected command patterns used to remove command history or clear local logs.",
			Category:    "defense-evasion",
			Mitre:       "T1070.003",
			Severity:    SeverityLow,
			Pattern:     `(?i)(history\s+-c|unset\s+HISTFILE|truncate\s+-s\s+0\s+/var/log|wevtutil\s+cl\s+)`,
			Target:      TargetContent,
		},
		{
			ID:          "ATK-DEF-002",
			Title:       "Security tooling disablement marker",
			Description: "Detected command patterns attempting to disable endpoint/security controls.",
			Category:    "defense-evasion",
			Mitre:       "T1562.001",
			Severity:    SeverityLow,
			Pattern:     `(?i)(setenforce\s+0|systemctl\s+stop\s+(auditd|falco)|ufw\s+disable|iptables\s+-F|disable(defender|edr))`,
			Target:      TargetContent,
		},
		{
			ID:          "ATK-DEF-003",
			Title:       "Dynamic linker hijacking variable",
			Description: "Detected linker environment variables that may be abused for stealth execution flow hijacking.",
			Category:    "defense-evasion",
			Mitre:       "T1574.006",
			Severity:    SeverityLow,
			Pattern:     `(?i)\b(LD_PRELOAD|LD_LIBRARY_PATH|DYLD_INSERT_LIBRARIES|COR_PROFILER)\b`,
			Target:      TargetContent,
		},
		{
			ID:          "ATK-DEF-004",
			Title:       "Hidden or immutable file manipulation marker",
			Description: "Detected file attribute modification patterns used to hide or lock malicious artifacts.",
			Category:    "defense-evasion",
			Mitre:       "T1564.001",
			Severity:    SeverityLow,
			Pattern:     `(?i)\b(chattr\s+\+i|attrib\s+\+h|setfattr|xattr\s+-w)\b`,
			Target:      TargetContent,
		},
		{
			ID:          "ATK-DEF-005",
			Title:       "Obfuscated command decode chain",
			Description: "Detected common shell decode/eval chain used to obfuscate command payloads.",
			Category:    "defense-evasion",
			Mitre:       "T1027.010",
			Severity:    SeverityLow,
			Pattern:     `(?i)(base64\s+-d.{0,80}\|\s*(bash|sh|zsh)|echo\s+[A-Za-z0-9+/=]{40,}\s*\|\s*base64\s+-d)`,
			Target:      TargetContent,
		},
		{
			ID:          "ATK-DEF-006",
			Title:       "eBPF program load or attach marker",
			Description: "Detected command/API markers for eBPF program load/attach operations that can be abused for stealth rootkit behavior.",
			Category:    "defense-evasion",
			Mitre:       "T1562.001",
			Severity:    SeverityLow,
			Pattern:     `(?i)(bpftool\s+(prog|map|net)\b|tc\s+filter\s+add.{0,120}\bbpf\b|bpf\(\s*BPF_PROG_LOAD)`,
			Target:      TargetContent,
		},
		{
			ID:          "ATK-DEF-007",
			Title:       "eBPF tracepoint concealment marker",
			Description: "Detected tracepoint/kprobe phrasing combined with concealment semantics, suggesting telemetry blinding behavior.",
			Category:    "defense-evasion",
			Mitre:       "T1562.001",
			Severity:    SeverityLow,
			Pattern:     `(?i)(kprobe|kretprobe|tracepoint|fentry|fexit).{0,120}(hide|conceal|drop|blind|mask)`,
			Target:      TargetContent,
		},
		{
			ID:          "ATK-DEF-008",
			Title:       "eBPF filesystem tampering marker",
			Description: "Detected mutation operations against /sys/fs/bpf that can alter or remove runtime visibility primitives.",
			Category:    "defense-evasion",
			Mitre:       "T1562.001",
			Severity:    SeverityLow,
			Pattern:     `(?i)(mount\s+-t\s+bpf|umount\s+/sys/fs/bpf|rm\s+-rf\s+/sys/fs/bpf|chown\s+.*\s+/sys/fs/bpf)`,
			Target:      TargetContent,
		},
		{
			ID:          "ATK-DEF-009",
			Title:       "Long path truncation evasion path",
			Description: "Detected path length beyond common eBPF stack visibility thresholds; deeply nested payload paths can impair runtime context.",
			Category:    "defense-evasion",
			Mitre:       "T1027",
			Severity:    SeverityLow,
			Pattern:     `(?s)^.{513,}$`,
			Target:      TargetPath,
		},
		{
			ID:          "ATK-DEF-010",
			Title:       "Pinned eBPF object path marker",
			Description: "Detected pinned eBPF object paths in bpffs, which should be reviewed for unauthorized persistence or masking hooks.",
			Category:    "defense-evasion",
			Mitre:       "T1543",
			Severity:    SeverityLow,
			Pattern:     `(?i)/sys/fs/bpf/[a-z0-9._/-]+`,
			Target:      TargetContent,
		},

		// Lateral Movement (TA0008).
		{
			ID:          "ATK-LAT-001",
			Title:       "Remote service execution utility marker",
			Description: "Detected use of utilities commonly associated with remote service lateral movement.",
			Category:    "lateral-movement",
			Mitre:       "T1021",
			Severity:    SeverityMedium,
			Pattern:     `(?i)\b(psexec|wmic\s+/node:|winrm|invoke-command\s+-computername)\b`,
			Target:      TargetContent,
		},
		{
			ID:          "ATK-LAT-002",
			Title:       "SSH lateral movement marker",
			Description: "Detected ssh/scp/rsync patterns that frequently appear in lateral movement workflows.",
			Category:    "lateral-movement",
			Mitre:       "T1021.004",
			Severity:    SeverityMedium,
			Pattern:     `(?i)\b(sshpass|scp\s+[^#\n]{0,200}@|rsync\s+[^#\n]{0,200}@)\b`,
			Target:      TargetContent,
		},
		{
			ID:          "ATK-LAT-003",
			Title:       "SMB/admin-share movement marker",
			Description: "Detected SMB admin-share command usage often linked to host-to-host propagation.",
			Category:    "lateral-movement",
			Mitre:       "T1021.002",
			Severity:    SeverityMedium,
			Pattern:     `(?i)(\\\\[a-z0-9._-]+\\[a-z$._-]+|net\s+use\s+\\\\)`,
			Target:      TargetContent,
		},
		{
			ID:          "ATK-LAT-004",
			Title:       "IDE/remote tunnel movement marker",
			Description: "Detected command patterns associated with IDE tunnels and remote development pivots.",
			Category:    "lateral-movement",
			Mitre:       "T1219.001",
			Severity:    SeverityMedium,
			Pattern:     `(?i)\b(code\s+tunnel|ssh\s+-R\s+|ssh\s+-L\s+|tailscale\s+funnel)\b`,
			Target:      TargetContent,
		},

		// Collection (TA0009).
		{
			ID:          "ATK-COL-001",
			Title:       "Sensitive file archival for staging",
			Description: "Detected archive operations targeting high-value credential material before exfiltration.",
			Category:    "collection",
			Mitre:       "T1560",
			Severity:    SeverityLow,
			Pattern:     `(?i)\b(tar|zip|7z)\b.{0,180}(\.aws|\.ssh|kubernetes\.io/serviceaccount|id_rsa|credentials)`,
			Target:      TargetContent,
		},
		{
			ID:          "ATK-COL-002",
			Title:       "Browser/session credential file access marker",
			Description: "Detected references to browser credential or cookie stores often collected for session hijacking.",
			Category:    "collection",
			Mitre:       "T1185",
			Severity:    SeverityLow,
			Pattern:     `(?i)(cookies\.sqlite|login data|key4\.db|local state|sessionstore\.jsonlz4)`,
			Target:      TargetContent,
		},
		{
			ID:          "ATK-COL-003",
			Title:       "Screen or clipboard capture marker",
			Description: "Detected commands associated with screenshot or clipboard collection activity.",
			Category:    "collection",
			Mitre:       "T1113",
			Severity:    SeverityLow,
			Pattern:     `(?i)\b(screencapture|xwd\s+-root|import\s+-window\s+root|pbpaste|xclip\s+-selection\s+clipboard)\b`,
			Target:      TargetContent,
		},
		{
			ID:          "ATK-COL-004",
			Title:       "Kubernetes broad secret collection marker",
			Description: "Detected broad kube secret enumeration patterns indicating high-volume collection intent.",
			Category:    "collection",
			Mitre:       "T1530",
			Severity:    SeverityLow,
			Pattern:     `(?i)kubectl\s+get\s+secrets?\s+(-A|--all-namespaces)`,
			Target:      TargetContent,
		},
		{
			ID:          "ATK-COL-005",
			Title:       "Process memory collection marker",
			Description: "Detected process memory collection commands associated with credential/token harvesting.",
			Category:    "collection",
			Mitre:       "T1003.007",
			Severity:    SeverityLow,
			Pattern:     `(?i)(/proc/\d+/mem|gcore\s+\d+|procdump(\.exe)?\b|process_vm_readv)`,
			Target:      TargetContent,
		},

		// Command and Control (TA0011).
		{
			ID:          "ATK-C2-001",
			Title:       "Tunnel-based C2 channel marker",
			Description: "Detected common tunneling services frequently abused for C2 and covert exfiltration channels.",
			Category:    "command-control",
			Mitre:       "T1090.003",
			Severity:    SeverityLow,
			Pattern:     `(?i)\b(trycloudflare\.com|cloudflared\s+tunnel|ngrok\.io|localtunnel\.me)\b`,
			Target:      TargetContent,
		},
		{
			ID:          "ATK-C2-002",
			Title:       "DNS command channel marker",
			Description: "Detected DNS TXT query style patterns frequently used for dead-drop or beaconing channels.",
			Category:    "command-control",
			Mitre:       "T1071.004",
			Severity:    SeverityLow,
			Pattern:     `(?i)\b(nslookup|dig)\b.{0,80}\b(-q=txt|txt)\b`,
			Target:      TargetContent,
		},
		{
			ID:          "ATK-C2-003",
			Title:       "Reverse shell construction marker",
			Description: "Detected reverse shell command fragments associated with interactive command-and-control setup.",
			Category:    "command-control",
			Mitre:       "T1059",
			Severity:    SeverityLow,
			Pattern:     `(?i)(/dev/tcp/\d{1,3}(?:\.\d{1,3}){3}/\d+|nc\s+-e\s+/bin/(sh|bash)|bash\s+-i\s+>&\s+/dev/tcp/)`,
			Target:      TargetContent,
		},
		{
			ID:          "ATK-C2-004",
			Title:       "Legitimate remote access tool marker",
			Description: "Detected remote access tooling names often abused for persistence and command-and-control.",
			Category:    "command-control",
			Mitre:       "T1219",
			Severity:    SeverityLow,
			Pattern:     `(?i)\b(teamviewer|anydesk|screenconnect|logmein|rustdesk)\b`,
			Target:      TargetContent,
		},
		{
			ID:          "ATK-C2-005",
			Title:       "Potential file exfiltration over HTTP POST",
			Description: "Detected HTTP POST upload patterns that may indicate data exfiltration over web protocols.",
			Category:    "command-control",
			Mitre:       "T1041",
			Severity:    SeverityLow,
			Pattern:     `(?i)\bcurl\b.{0,200}\b(-F|--data-binary|--upload-file)\b.{0,200}https?://`,
			Target:      TargetContent,
		},
		{
			ID:          "ATK-PER-006",
			Title:       "Startup folder msbuild persistence indicator",
			Description: "Detected startup-folder persistence marker matching campaign behavior.",
			Category:    "persistence",
			Mitre:       "T1547.001",
			Severity:    SeverityHigh,
			Pattern:     `(?i)(startup[/\\].*msbuild\.exe|msbuild\.exe\.lock)`,
			Target:      TargetContent,
		},
		{
			ID:          "ATK-PER-007",
			Title:       "User-level systemd persistence commands",
			Description: "Detected systemd user-service persistence pattern.",
			Category:    "persistence",
			Mitre:       "T1546.016",
			Severity:    SeverityHigh,
			Pattern:     `(?i)(systemctl\s+--user\s+(enable|start|daemon-reload)|~/.config/systemd/user)`,
			Target:      TargetContent,
		},
		{
			ID:          "ATK-MEM-001",
			Title:       "Process memory scraping indicator",
			Description: "Detected /proc/*/mem access pattern linked to credential harvesting behavior.",
			Category:    "credential-access",
			Mitre:       "T1552.001",
			Severity:    SeverityHigh,
			Pattern:     `(?i)/proc/(pid|\d+)/mem`,
			Target:      TargetContent,
		},
		{
			ID:          "ATK-K8S-001",
			Title:       "Kubernetes secret sweep indicator",
			Description: "Detected marker for broad Kubernetes secret collection behavior.",
			Category:    "credential-access",
			Mitre:       "T1552.001",
			Severity:    SeverityHigh,
			Pattern:     `(?i)(k8s secrets?\s*\(all namespaces\)|/var/run/secrets/kubernetes\.io/serviceaccount)`,
			Target:      TargetContent,
		},
		{
			ID:          "ATK-IMDS-001",
			Title:       "Cloud metadata credential access indicator",
			Description: "Detected IMDS access pattern (169.254.169.254) used for cloud credential harvesting.",
			Category:    "credential-access",
			Mitre:       "T1552.005",
			Severity:    SeverityHigh,
			Pattern:     `(?i)(\b169\.254\.169\.254\b|latest/meta-data|metadata/v1)`,
			Target:      TargetContent,
		},
		{
			ID:          "ATK-SWEEP-001",
			Title:       "Credential sweep file target indicator",
			Description: "Detected references to high-value credential file paths targeted by supply-chain payloads.",
			Category:    "credential-access",
			Mitre:       "T1552.001",
			Severity:    SeverityMedium,
			Pattern:     `(?i)(~/.aws/|~/.config/gcloud/|~/.azure/|~/.docker/config\.json|~/.ssh/|~/.npmrc|(^|[\s"'/])\.env([\s"'/\\:]|$)|k8s service account tokens?|/var/run/secrets/kubernetes\.io/serviceaccount)`,
			Target:      TargetContent,
		},
		{
			ID:          "ATK-EXFIL-001",
			Title:       "Generic credential exfil behavior marker",
			Description: "Detected patterns that may indicate credential collection and packaging for exfiltration.",
			Category:    "credential-access",
			Mitre:       "T1552.001",
			Severity:    SeverityHigh,
			Pattern:     `(?i)(tar|zip).{0,80}(\.aws|\.ssh|\.npmrc|docker/config\.json|kubernetes\.io/serviceaccount)`,
			Target:      TargetContent,
		},
		{
			ID:          "ATK-MEMDUMP-001",
			Title:       "Runner memory dumping primitive marker",
			Description: "Detected process-memory dumping primitives frequently used to bypass secret redaction in CI/CD logs.",
			Category:    "credential-access",
			Mitre:       "T1003.007",
			Severity:    SeverityCritical,
			Pattern:     `(?i)(/proc/\d+/mem|process_vm_readv|gcore\s+\d+|ptrace\s*\(|dd\s+if=/proc/\d+/mem)`,
			Target:      TargetContent,
			Remediation: "Remove memory-dumping or ptrace usage from CI and application code. Enable seccomp, AppArmor, or Yama ptrace restrictions on runners to block these primitives.",
		},
		{
			ID:          "ATK-WIPER-001",
			Title:       "Region-targeted wiper logic",
			Description: "Detected conditional region/language checks linked to destructive wiper behavior targeting specific locales.",
			Category:    "npm",
			Mitre:       "T1204.002",
			Severity:    SeverityHigh,
			Pattern:     `(?i)(timezone|tz|locale|lang).{0,40}(iran|tehran|farsi|\bfa\b)`,
			Target:      TargetContent,
		},
		{
			ID:          "ATK-C2-006",
			Title:       "Cloudflare quick tunnel abuse",
			Description: "Detected trycloudflare tunnel domain often used as exfil relay in supply-chain campaigns.",
			Category:    "exfiltration",
			Mitre:       "T1572",
			Severity:    SeverityMedium,
			Pattern:     `(?i)\b([a-z0-9-]+\.)?trycloudflare(?:\.|\[\.\])com\b`,
			Target:      TargetContent,
		},
		{
			ID:          "CI-EXFIL-001",
			Title:       "Actions token exfiltration flow marker",
			Description: "Detected command flow that combines GitHub Actions token variables with outbound web requests.",
			Category:    "credential-access",
			Mitre:       "T1552.001",
			Severity:    SeverityCritical,
			Pattern:     `(?i)((ACTIONS_RUNTIME_TOKEN|GITHUB_TOKEN|ACTIONS_ID_TOKEN_REQUEST_TOKEN).{0,120}(curl|wget|Invoke-WebRequest|Invoke-RestMethod)|\b(curl|wget)\b.{0,200}\$(ACTIONS_RUNTIME_TOKEN|GITHUB_TOKEN|ACTIONS_ID_TOKEN_REQUEST_TOKEN)\b)`,
			Target:      TargetContent,
			Remediation: "Remove outbound requests that embed CI tokens. Use OIDC to cloud roles instead of long-lived tokens, and never pipe GITHUB_TOKEN or runtime tokens to the network.",
		},
	}
}
