package rules

import "regexp"

// nonCodeSurfacesRules detects threats in files that traditional code scanners ignore:
// git metadata that executes code, package manager configs that redirect trust,
// agent instruction surfaces, and IDE configs with execution capability.
//
//nolint:funlen // declarative rule table
func nonCodeSurfacesRules() []Rule {
	return []Rule{
		// Git metadata poisoning: .gitattributes smudge/clean filters execute
		// arbitrary commands on checkout/commit. This is one of the most dangerous
		// git features and is almost never audited.
		{
			ID:          "SCM-GIT-001",
			Title:       "Git attribute with smudge/clean filter",
			Description: "A .gitattributes file defines a smudge or clean filter, which executes arbitrary commands during git checkout or git add. An attacker who controls .gitattributes can execute code on every developer who clones the repo.",
			Category:    "non-code-surface",
			Mitre:       "T1059",
			Severity:    SeverityCritical,
			Pattern:     `(?i)\b(filter|diff|merge)\s*=\s*\S+`,
			Target:      TargetContent,
			Remediation: "Remove smudge/clean filters or replace them with audited, minimal scripts. Treat .gitattributes like executable code and block arbitrary filter commands.",
			PathPattern: regexp.MustCompile(`(?i)(^|/)\.gitattributes$`),
		},
		// .gitmodules: submodules pull external code into the repo at clone time.
		// URL hijacking or branch/tag manipulation enables supply chain compromise.
		{
			ID:          "SCM-GIT-002",
			Title:       "Git submodule with external URL",
			Description: "A .gitmodules file references an external repository URL. Submodules execute git operations at clone/update time and can be redirected to attacker-controlled repositories via URL hijacking or branch manipulation.",
			Category:    "non-code-surface",
			Mitre:       "T1195.002",
			Severity:    SeverityMedium,
			Pattern:     `(?i)url\s*=\s*(https?://|git://|git@)`,
			Target:      TargetContent,
			PathPattern: regexp.MustCompile(`(?i)(^|/)\.gitmodules$`),
		},
		// Committed git hooks execute on every git operation.
		{
			ID:          "SCM-GIT-003",
			Title:       "Committed git hook script",
			Description: "A git hook script is committed in the repository. Committed hooks in .githooks/, .husky/, or scripts/hooks/ execute automatically on git operations (commit, push, merge) for every developer who configures the hook path.",
			Category:    "non-code-surface",
			Mitre:       "T1059",
			Severity:    SeverityHigh,
			Pattern:     `(?i)(^|/)(\.githooks|\.husky|\.git/hooks|scripts/hooks)/(pre-commit|post-commit|pre-push|post-merge|pre-receive|post-receive|prepare-commit-msg|commit-msg|pre-rebase|post-checkout|post-rewrite)`,
			Target:      TargetPath,
		},
		// .pre-commit-config.yaml downloads and executes external hooks.
		{
			ID:          "SCM-GIT-004",
			Title:       "Pre-commit config with external hook source",
			Description: "A .pre-commit-config.yaml file references external hook repositories. Pre-commit hooks download and execute code from these sources on every commit, creating a supply chain dependency.",
			Category:    "non-code-surface",
			Mitre:       "T1195.002",
			Severity:    SeverityMedium,
			Pattern:     `(?i)repo:\s*(https?://|git://|git@)`,
			Target:      TargetContent,
			PathPattern: regexp.MustCompile(`(?i)(^|/)\.pre-commit-config\.ya?ml$`),
		},

		// Package manager config poisoning: these files redirect where packages
		// are fetched from, enabling dependency confusion and registry hijacking.
		{
			ID:          "SCM-PKG-001",
			Title:       "npm/yarn config with custom registry",
			Description: "An .npmrc or .yarnrc file defines a registry URL. Custom registries can serve malicious packages that shadow legitimate ones (dependency confusion). Verify the registry is a trusted, organization-controlled mirror.",
			Category:    "non-code-surface",
			Mitre:       "T1195.002",
			Severity:    SeverityHigh,
			Pattern:     `(?i)registry\s*=\s*https?://`,
			Target:      TargetContent,
			PathPattern: regexp.MustCompile(`(?i)(^|/)(\.npmrc|\.yarnrc(\.ya?ml)?)$`),
		},
		{
			ID:          "SCM-PKG-002",
			Title:       "pip/Python config with custom index",
			Description: "A pip config or pyproject.toml defines a package index URL. Custom indexes can serve malicious packages. Verify the index is a trusted, organization-controlled mirror.",
			Category:    "non-code-surface",
			Mitre:       "T1195.002",
			Severity:    SeverityHigh,
			Pattern:     `(?i)(index-url|extra-index-url)\s*=\s*https?://`,
			Target:      TargetContent,
			PathPattern: regexp.MustCompile(`(?i)(^|/)(\.pypirc|pip\.conf|pyproject\.toml|setup\.cfg)$`),
		},
		{
			ID:          "SCM-PKG-003",
			Title:       "Package config with install-time script hook",
			Description: "A package configuration file defines scripts that execute during install, build, or publish lifecycle events. These hooks run with the installing user's permissions and can execute arbitrary code.",
			Category:    "non-code-surface",
			Mitre:       "T1059",
			Severity:    SeverityMedium,
			Pattern:     `(?i)"(preinstall|postinstall|preuninstall|postuninstall|prepublish|prepare)"\s*:`,
			Target:      TargetContent,
			PathPattern: regexp.MustCompile(`(?i)(^|/)package\.json$`),
		},

		// Agent instruction surface detection: files that AI agents read as
		// authoritative instructions. This is the 2025+ attack surface.
		{
			ID:          "AGT-ART-004",
			Title:       "Agent/IDE instruction file detected",
			Description: "Detected a file that AI agents and IDE tools read as authoritative instructions. These files define agent behavior, tool permissions, and code generation patterns. They are high-value targets for prompt injection and should be reviewed for malicious directives.",
			Category:    "non-code-surface",
			Mitre:       "T1195.002",
			Severity:    SeverityInfo,
			Pattern:     `(?i)(^|/)(\.cursorrules|\.cursor/rules/|\.claude/|\.copilot-instructions\.md|\.github/copilot-instructions\.md|AGENTS\.md|\.aider|\.continue/|RULES\.md|\.windsurfrules)`,
			Target:      TargetPath,
		},
		{
			ID:          "AGT-ART-005",
			Title:       "IDE task/launch config with command execution",
			Description: "An IDE configuration file defines tasks or launch configurations that execute shell commands. Committed .vscode/tasks.json or launch.json files execute commands when developers open the project, creating a code execution vector.",
			Category:    "non-code-surface",
			Mitre:       "T1059",
			Severity:    SeverityMedium,
			Pattern:     `(?i)"(command|program|runtimeExecutable|preLaunchTask)"\s*:\s*"`,
			Target:      TargetContent,
			PathPattern: regexp.MustCompile(`(?i)(^|/)\.vscode/(tasks|launch)\.json$`),
		},
		{
			ID:          "AGT-ART-006",
			Title:       "Devcontainer config with privileged execution",
			Description: "A devcontainer configuration requests privileged mode, host mounts, or post-create commands. Devcontainers auto-execute on project open in VS Code/Codespaces, making them a high-value target for code execution.",
			Category:    "non-code-surface",
			Mitre:       "T1059",
			Severity:    SeverityHigh,
			Pattern:     `(?i)("privileged"\s*:\s*true|"postCreateCommand"|"postStartCommand"|"postAttachCommand"|"--privileged"|"/var/run/docker\.sock")`,
			Target:      TargetContent,
			PathPattern: regexp.MustCompile(`(?i)(^|/)\.devcontainer(/[^/]+)?/devcontainer\.json$`),
		},
		{
			ID:          "SCM-TRUST-001",
			Title:       "GitHub Action reference pinned to mutable ref",
			Description: "Detected action reference pinned by branch/tag/latest instead of immutable commit SHA.",
			Category:    "scm-trust",
			Mitre:       "T1195.002",
			Severity:    SeverityHigh,
			Pattern:     `(?i)\buses:\s*[a-z0-9_.-]+/[a-z0-9_.-]+@(main|master|latest|v?\d+(?:\.\d+){0,2})\b`,
			Target:      TargetContent,
		},
		{
			ID:          "SCM-TRUST-002",
			Title:       "Remote bootstrap script execution marker",
			Description: "Detected direct remote script bootstrap execution command frequently abused in supply-chain pivots.",
			Category:    "scm-trust",
			Mitre:       "T1204.002",
			Severity:    SeverityHigh,
			Pattern:     `(?i)\b(curl|wget)\b.{0,220}(raw\.githubusercontent\.com|gist\.githubusercontent\.com|install\.sh|bootstrap\.sh).{0,120}\|\s*(bash|sh|zsh)`,
			Target:      TargetContent,
		},
		{
			ID:          "SCM-TRUST-003",
			Title:       "Container image tag pull without digest pin",
			Description: "Detected container image pull/build references with mutable tags and no digest pin.",
			Category:    "scm-trust",
			Mitre:       "T1195.002",
			Severity:    SeverityMedium,
			Pattern:     `(?i)\b(docker\s+(pull|run)\s+[a-z0-9._/\-]+:[a-z0-9._-]+(?:\s|$)|image:\s*[a-z0-9._/\-]+:[a-z0-9._-]+(?:\s|$))`,
			Target:      TargetContent,
		},
		{
			ID:          "SCM-TRUST-004",
			Title:       "Git force-push to protected refs marker",
			Description: "Detected force push to protected references, a high-risk primitive for history or tag tampering.",
			Category:    "scm-trust",
			Mitre:       "T1195.002",
			Severity:    SeverityHigh,
			Pattern:     `(?i)\bgit\s+push\b.{0,120}--force\b.{0,120}(main|master|refs/tags|refs/heads/)`,
			Target:      TargetContent,
		},
		{
			ID:          "SCM-TAG-001",
			Title:       "Mutable tag force-update operation marker",
			Description: "Detected git operations that rewrite trusted tags, a common primitive in tag poisoning supply-chain attacks.",
			Category:    "github-actions",
			Mitre:       "T1195.002",
			Severity:    SeverityHigh,
			Pattern:     `(?i)(git\s+tag\s+-f\b|git\s+push\b.{0,80}--force.{0,40}--tags\b|git\s+push\b.{0,120}:refs/tags/)`,
			Target:      TargetContent,
		},

		// Dependency bot configuration weaknesses (CI-DEPBOT-001–009).
		{
			ID:             "CI-DEPBOT-001",
			Title:          "Dependency bot with no minimum release age",
			Description:    "Renovate or Dependabot config has no minimumReleaseAge/stabilityDays setting. Without a release age gate, a compromised upstream package triggers a PR within minutes of publication — and CI runs install hooks (preinstall/postinstall) on the runner before any human reviews the PR. The runner is compromised from the PR check alone, no merge required.",
			Category:       "ci-depbot",
			Mitre:          "T1195.002",
			Severity:       SeverityCritical,
			Pattern:        `(?i)"extends"\s*:\s*\[`,
			Target:         TargetContent,
			PathPattern:    regexp.MustCompile(`(?i)(^|/)(\.?(renovate|github/renovate)(\.json5?|\.ya?ml)|\.github/dependabot\.ya?ml)$`),
			ExcludePattern: regexp.MustCompile(`(?i)minimumReleaseAge|stabilityDays`),
		},
		{
			ID:          "CI-DEPBOT-002",
			Title:       "Dependency bot groups minor and patch updates",
			Description: "Grouping minor and patch updates into single PRs reduces review granularity. A malicious minor version bump can be hidden alongside benign patches.",
			Category:    "ci-depbot",
			Mitre:       "T1195.002",
			Severity:    SeverityMedium,
			Pattern:     `(?i)"groupName"\s*:\s*"[^"]*(?:minor|patch)[^"]*"`,
			Target:      TargetContent,
			PathPattern: regexp.MustCompile(`(?i)(^|/)(\.?(renovate|github/renovate)(\.json5?|\.ya?ml)|\.github/dependabot\.ya?ml)$`),
		},
		{
			ID:          "CI-DEPBOT-003",
			Title:       "Dependency bot automerge enabled",
			Description: "Automerge allows dependency updates to land without human review. A compromised package version can be merged automatically.",
			Category:    "ci-depbot",
			Mitre:       "T1195.002",
			Severity:    SeverityHigh,
			Pattern:     `(?i)"automerge"\s*:\s*true`,
			Target:      TargetContent,
			PathPattern: regexp.MustCompile(`(?i)(^|/)(\.?(renovate|github/renovate)(\.json5?|\.ya?ml)|\.github/dependabot\.ya?ml)$`),
		},
		{
			ID:          "CI-DEPBOT-004",
			Title:       "Dependency bot uses mutable range strategy",
			Description: "Using rangeStrategy 'bump' instead of 'pin' allows future installs to resolve newer, potentially compromised versions within the range.",
			Category:    "ci-depbot",
			Mitre:       "T1195.002",
			Severity:    SeverityMedium,
			Pattern:     `(?i)"rangeStrategy"\s*:\s*"bump"`,
			Target:      TargetContent,
			PathPattern: regexp.MustCompile(`(?i)(^|/)(\.?(renovate|github/renovate)(\.json5?|\.ya?ml)|\.github/dependabot\.ya?ml)$`),
		},
		{
			ID:          "CI-DEPBOT-005",
			Title:       "Dependency bot automerge on security-sensitive paths",
			Description: "Automerge is combined with matchFileNames targeting CI/CD, Dockerfiles, or agent config paths. Automatically merging changes to these files bypasses human review of security-critical configurations.",
			Category:    "ci-depbot",
			Mitre:       "T1195.002",
			Severity:    SeverityHigh,
			Pattern:     `(?i)"automerge"\s*:\s*true.{0,500}"matchFileNames"\s*:\s*\[[^\]]*(?:\.tekton|\.github|Dockerfile|\.claude)`,
			Target:      TargetContent,
			PathPattern: regexp.MustCompile(`(?i)(^|/)(\.?(renovate|github/renovate)(\.json5?|\.ya?ml)|\.github/dependabot\.ya?ml)$`),
		},
		{
			ID:             "CI-DEPBOT-006",
			Title:          "Dependency bot missing vulnerability alerts",
			Description:    "Renovate config does not enable vulnerabilityAlerts or osvVulnerabilityAlerts. Without these, known vulnerable dependency versions are not prioritized for update.",
			Category:       "ci-depbot",
			Mitre:          "T1195.002",
			Severity:       SeverityMedium,
			Pattern:        `(?i)"extends"\s*:\s*\[`,
			Target:         TargetContent,
			PathPattern:    regexp.MustCompile(`(?i)(^|/)(\.?(renovate|github/renovate)(\.json5?|\.ya?ml)|\.github/dependabot\.ya?ml)$`),
			ExcludePattern: regexp.MustCompile(`(?i)vulnerabilityAlerts|osvVulnerabilityAlerts`),
		},
		{
			ID:          "CI-DEPBOT-007",
			Title:       "Dependency bot disables Go module updates",
			Description: "Renovate config disables gomod manager or disables all Go module update types. This means Go dependency vulnerabilities are never automatically remediated.",
			Category:    "ci-depbot",
			Mitre:       "T1195.002",
			Severity:    SeverityHigh,
			Pattern:     `(?i)"matchManagers"\s*:\s*\[\s*"gomod"\s*\].{0,500}"enabled"\s*:\s*false|"matchUpdateTypes"\s*:\s*\[.{0,500}\].{0,200}"matchManagers"\s*:\s*\[\s*"gomod"\s*\]`,
			Target:      TargetContent,
			PathPattern: regexp.MustCompile(`(?i)(^|/)(\.?(renovate|github/renovate)(\.json5?|\.ya?ml)|\.github/dependabot\.ya?ml)$`),
		},
		{
			ID:             "CI-DEPBOT-008",
			Title:          "Dependabot with no reviewers configured",
			Description:    "Dependabot config has no reviewers or assignees set. Without explicit reviewers, dependency update PRs may be merged without security review.",
			Category:       "ci-depbot",
			Mitre:          "T1195.002",
			Severity:       SeverityMedium,
			Pattern:        `(?i)package-ecosystem:`,
			Target:         TargetContent,
			PathPattern:    regexp.MustCompile(`(?i)(^|/)\.github/dependabot\.ya?ml$`),
			ExcludePattern: regexp.MustCompile(`(?i)(reviewers:|assignees:)`),
		},
		{
			ID:          "CI-DEPBOT-009",
			Title:       "Dependabot allows all dependency types",
			Description: "Dependabot config uses allow with dependency-type: all, which includes both direct and transitive dependencies. This broadens the attack surface for supply chain substitution.",
			Category:    "ci-depbot",
			Mitre:       "T1195.002",
			Severity:    SeverityMedium,
			Pattern:     `(?i)dependency-type:\s*(all|production)`,
			Target:      TargetContent,
			PathPattern: regexp.MustCompile(`(?i)(^|/)\.github/dependabot\.ya?ml$`),
		},

		// Container image trust (SCM-TRUST-005).
		{
			ID:          "SCM-TRUST-005",
			Title:       "Container image from personal registry namespace",
			Description: "Dockerfile FROM references a personal user namespace on a container registry rather than an organizational account. If the personal account is compromised, all builds using this base image are compromised.",
			Category:    "scm-trust",
			Mitre:       "T1195.002",
			Severity:    SeverityHigh,
			Pattern:     `(?i)FROM\s+(quay\.io|ghcr\.io|docker\.io)/[a-z][a-z0-9_-]{1,30}/[a-z]`,
			Target:      TargetContent,
			PathPattern: regexp.MustCompile(`(?i)(^|/)(Dockerfile|Containerfile)`),
		},

		// Cargo build-script supply chain (DEP-CARGO-001).
		{
			ID:          "DEP-CARGO-001",
			Title:       "Cargo build.rs with network access",
			Description: "A Rust build script (build.rs) uses network or process APIs, which execute during cargo build with full host privileges.",
			Category:    "supply-chain",
			Mitre:       "T1195.002",
			Severity:    SeverityHigh,
			Pattern:     `(?i)(std::net::|std::process::Command|reqwest::|ureq::|hyper::|curl::|TcpStream|UdpSocket)`,
			Target:      TargetContent,
			PathPattern: regexp.MustCompile(`(?i)(^|/)build\.rs$`),
		},

		// Python install hooks (DEP-PY-001–002).
		{
			ID:          "DEP-PY-001",
			Title:       "Python setup.py with install hook",
			Description: "A setup.py defines install or post-install commands that run arbitrary code during pip install.",
			Category:    "supply-chain",
			Mitre:       "T1195.002",
			Severity:    SeverityHigh,
			Pattern:     `(?i)(cmdclass|install_requires|setup\s*\()`,
			Target:      TargetContent,
			PathPattern: regexp.MustCompile(`(?i)(^|/)setup\.py$`),
		},
		{
			ID:          "DEP-PY-002",
			Title:       "pyproject.toml with build-system scripts entry",
			Description: "A pyproject.toml defines project.scripts or build-system hooks that execute during install.",
			Category:    "supply-chain",
			Mitre:       "T1195.002",
			Severity:    SeverityMedium,
			Pattern:     `(?i)\[project\.scripts\]|\[build-system\]`,
			Target:      TargetContent,
			PathPattern: regexp.MustCompile(`(?i)(^|/)pyproject\.toml$`),
		},
	}
}
