package rules

// fallbackLiteralHints supplies Aho-Corasick keywords when ExtractLiteralHint returns empty
// (common when patterns start with (?i) and a leading parenthesized alternation). Each value
// must be present in every match at any offset (case-insensitive), or true positives may be
// skipped during prefilter.
var fallbackLiteralHints = map[string]string{
	"AGT-EXP-002":     "toolchoice",
	"AGT-EXP-005":     "memory",
	"AGT-EXP-006":     "tool_output",
	"AGT-EXP-008":     "install",
	"AGT-EXP-010":     "user_",
	"AGT-MCP-001":     "important",
	"AGT-MCP-005":     "powershell",
	"AGT-MCP-006":     "files:",
	"AGT-MCP-007":     "access_token",
	"AGT-MCP-011":     "token_endpoint",
	"AGT-MCP-019":     "authorization",
	"AGT-MEM-002":     "guardrail",
	"AGT-MEM-003":     "remember",
	"AGT-MEM-004":     "memory",
	"AGT-MEM-005":     "vector",
	"AGT-OUT-001":     "https://",
	"AGT-OUT-002":     "system",
	"AGT-OUT-003":     "false positive",
	"AGT-SKL-003":     "curl",
	"AGT-SKL-004":     "base64",
	"AGT-SKL-005":     "password",
	"AGT-SKL-007":     ".ssh",
	"AGT-SKL-008":     "api key",
	"AGT-SKL-011":     "private key",
	"AGT-SKL-014":     "translate",
	"AGT-SKL-015":     "benign",
	"AGT-SKL-016":     "internal",
	"AGT-TRUST-003":   ".ssh",
	"AGT-TRUST-005":   "curl",
	"AGT-TRUST-006":   "rm -",
	"ATK-C2-001":      "cloudflare",
	"ATK-C2-002":      "nslookup",
	"ATK-C2-003":      "/dev/tcp",
	"ATK-C2-004":      "teamviewer",
	"ATK-COL-001":     ".aws",
	"ATK-COL-002":     "cookies",
	"ATK-COL-003":     "screencapture",
	"ATK-COL-005":     "/proc/",
	"ATK-DEF-001":     "history",
	"ATK-DEF-002":     "auditd",
	"ATK-DEF-003":     "ld_preload",
	"ATK-DEF-004":     "chattr",
	"ATK-DEF-005":     "base64",
	"ATK-DEF-006":     "bpftool",
	"ATK-DEF-007":     "kprobe",
	"ATK-DEF-008":     "/sys/fs/bpf",
	"ATK-EXE-002":     "powershell",
	"ATK-EXE-003":     "kubectl",
	"ATK-EXE-005":     "jndi:",
	"ATK-EXFIL-001":   ".aws",
	"ATK-IMDS-001":    "169.254",
	"ATK-K8S-001":     "kubernetes",
	"ATK-LAT-001":     "psexec",
	"ATK-LAT-002":     "sshpass",
	"ATK-LAT-004":     "tunnel",
	"ATK-MEMDUMP-001": "/proc/",
	"ATK-PER-002":     "authorized_keys",
	"ATK-PER-003":     ".bashrc",
	"ATK-PER-004":     "sitecustomize",
	"ATK-PER-005":     "launchagents",
	"ATK-PER-006":     "msbuild",
	"ATK-PER-007":     "systemctl",
	"ATK-SWEEP-001":   ".aws",
	"ATK-WIPER-001":   "timezone",
	"CI-ABUSE-001":    "self-hosted",
	"CI-BUILD-003":    "curl",
	"CI-BUILD-008":    "copy",
	"CI-ENV-001":      "api_key",
	"CI-ENV-002":      "postgres",
	"CI-ENV-003":      "password:",
	"CI-ENV-004":      "curl",
	"CI-EXFIL-001":    "github_token",
	"CI-GOV-002":      "auto-merge",
	"CI-SECRET-001":   "printenv",
	"CI-SECRET-002":   "bash",
	"CI-SECRET-003":   "curl",
	"CI-SECRET-004":   "echo",
	"CLOUD-ID-003":    "client_secret",
	"CLOUD-ID-004":    "oauth2",
	"CTR-ESC-001":     "privileged",
	"CTR-ESC-002":     "hostpid",
	"CTR-ESC-003":     "hostpath",
	"CTR-ESC-004":     "sys_admin",
	"CTR-ESC-005":     "docker.sock",
	"CTR-ESC-006":     "nsenter",
	"DEP-CARGO-001":   "reqwest",
	"DEP-PY-001":      "install_requires",
	"ENC-EXFIL-001":   "base64",
	"ENC-EXFIL-003":   "export",
	"ENC-EXFIL-010":   "export",
	"ENC-STEGO-001":   "base64",
	"IAC-ANS-001":     "vault",
	"IAC-HELM-002":    "helm",
	"RUGPULL-006":     "version",
	"SCM-GIT-001":     "filter",
	"SCM-PKG-003":     "preinstall",
	"SCM-TAG-001":     "git",
	"SCM-TRUST-002":   "raw.githubusercontent",
	"SCM-TRUST-003":   "docker",
}
