package rules

import "regexp"

// agenticSurfacesRules captures poisoning and abuse patterns in agent tooling ecosystems.
func agenticSurfacesRules() []Rule { //nolint:funlen // declarative rule table
	rules := []Rule{
		// Artifact discovery for agentic systems.
		{
			ID:          "AGT-ART-001",
			Title:       "Agent skill manifest detected",
			Description: "SKILL.md discovered; validate for prompt injection, malicious setup commands, and hidden instructions.",
			Category:    "artifact",
			Mitre:       "T1195.002",
			Severity:    SeverityInfo,
			Pattern:     `(?i)(^|/)skill\.md$`,
			Target:      TargetPath,
		},
		{
			ID:          "AGT-ART-002",
			Title:       "MCP configuration file detected",
			Description: "Potential MCP server configuration file discovered; inspect configured servers and startup commands.",
			Category:    "artifact",
			Mitre:       "T1195.002",
			Severity:    SeverityInfo,
			Pattern:     `(?i)(^|/)(mcp\.json|claude_desktop_config\.json)$`,
			Target:      TargetPath,
		},
		{
			ID:          "AGT-ART-003",
			Title:       "Persistent memory artifact detected",
			Description: "Memory artifact discovered; inspect for poisoned long-lived instructions or sensitive data persistence.",
			Category:    "artifact",
			Mitre:       "T1552.001",
			Severity:    SeverityInfo,
			Pattern:     `(?i)(^|/)(memory\.md|soul\.md|agent[_-]?memory\.(json|md)|conversation[_-]?memory\.(json|md))$`,
			Target:      TargetPath,
		},

		// Skills poisoning / prompt injection / malicious setup behaviors.
		{
			ID:          "AGT-SKL-001",
			Title:       "Prompt-injection override directive",
			Description: "Prompt text includes classic override directives used to bypass policy or system instructions.",
			Category:    "skills-poisoning",
			Mitre:       "T1204.002",
			Severity:    SeverityHigh,
			Pattern:     `(?i)(ignore (all|any )?(previous|prior) instructions|disregard .*instructions|override .*system prompt|developer mode|dan mode|jailbreak)`,
			Target:      TargetContent,
			Remediation: "Remove override and jailbreak language from skills and prompts. Keep agent instructions aligned with organizational policy and safety baselines.",
		},
		{
			ID:             "AGT-SKL-002",
			Title:          "Concealment directive in prompt or tool text",
			Description:    "Detected instruction to hide behavior from users, a common poisoning and exfiltration tactic.",
			Category:       "skills-poisoning",
			Mitre:          "T1036",
			Severity:       SeverityHigh,
			Pattern:        `(?i)(do not mention (this|that|to the user)|without telling (the )?user|hidden instruction|implementation detail only)`,
			Target:         TargetContent,
			Remediation:    "Delete concealment or hidden-instruction wording so users and reviewers see the full behavior. Split sensitive steps into approved, documented procedures instead.",
			ExcludePattern: regexp.MustCompile(`(?i)session.{0,20}lock|screen.{0,20}lock`),
		},
		{
			ID:              "AGT-SKL-003",
			Title:           "Remote script execution pipeline",
			Description:     "Detected one-liner download-and-execute pattern (curl/wget piped into shell/source).",
			Category:        "skills-poisoning",
			Mitre:           "T1059",
			Severity:        SeverityCritical,
			ConfidenceClass: ConfidenceDefinitive,
			Pattern:         `(?i)\b(curl|wget)\b.{0,180}\|\s*(bash|sh|zsh|source)\b`,
			Target:          TargetContent,
			Remediation:     "Replace download-and-pipe-to-shell with a reviewed install path: vendor the artifact, verify checksums or signatures, then run explicit commands from a locked script.",
		},
		{
			ID:              "AGT-SKL-004",
			Title:           "Obfuscated command decoding pattern",
			Description:     "Detected base64/eval decode pattern commonly used to obfuscate malicious setup instructions.",
			Category:        "skills-poisoning",
			Mitre:           "T1027",
			Severity:        SeverityCritical,
			ConfidenceClass: ConfidenceDefinitive,
			Pattern:         `(?i)(eval\s*\(.{0,120}base64\s*-d|base64\s*-d.{0,80}\|\s*(bash|sh|zsh)|powershell.{0,30}(-enc|-encodedcommand)\b)`,
			Target:          TargetContent,
			Remediation:     "Remove obfuscated decode-and-run steps. If payload is legitimate, check in clear text with code review; never execute encoded blobs from untrusted skills.",
		},
		{
			ID:          "AGT-SKL-005",
			Title:       "Password-protected archive execution",
			Description: "Detected installation sequence using password-protected archives, a common malware evasion technique.",
			Category:    "skills-poisoning",
			Mitre:       "T1027",
			Severity:    SeverityHigh,
			Pattern:     `(?i)\b(unzip|7z|tar)\b.{0,120}(-P|-p|--password)\b`,
			Target:      TargetContent,
			Remediation: "Avoid password-protected archives in automated setup. Use signed packages from a trusted registry or distribute secrets through a vault, not embedded passwords.",
		},
		{
			ID:          "AGT-SKL-006",
			Title:       "Direct executable launch after chmod",
			Description: "Detected direct execution of freshly downloaded binaries/scripts in setup flow.",
			Category:    "skills-poisoning",
			Mitre:       "T1204.002",
			Severity:    SeverityHigh,
			Pattern:     `(?i)chmod\s+\+x\s+\S+.{0,120}&&\s*\./\S+`,
			Target:      TargetContent,
			Remediation: "Do not mark-then-run freshly downloaded binaries in skills. Install via package manager or verify publisher signatures before execution.",
		},
		{
			ID:              "AGT-SKL-007",
			Title:           "Sensitive local file access directive",
			Description:     "Detected explicit references to high-value credential files in skill or tool instructions.",
			Category:        "skills-poisoning",
			Mitre:           "T1552.001",
			Severity:        SeverityCritical,
			ConfidenceClass: ConfidenceDefinitive,
			Pattern:         `(?i)(~/.ssh/id_rsa|~/.aws/credentials|~/.cursor/mcp\.json|/etc/shadow|~/.docker/config\.json)`,
			Target:          TargetContent,
			Remediation:     "Remove credential-path references from agent instructions. Use least-privilege tool scopes and secret references instead of steering agents toward key material.",
		},
		{
			ID:          "AGT-SKL-008",
			Title:       "Credential disclosure request pattern",
			Description: "Detected instruction pattern asking users or agents to print/share secrets in output.",
			Category:    "skills-poisoning",
			Mitre:       "T1552.001",
			Severity:    SeverityHigh,
			Pattern:     `(?i)(print|echo|share|paste|output).{0,60}\b(api key|token|secret|password|credential)\b`,
			Target:      TargetContent,
			Remediation: "Delete instructions that ask to print or paste secrets into chat or logs. Retrieve secrets from a vault or CI mask and never echo them in agent output.",
		},
		{
			ID:          "AGT-SKL-010",
			Title:       "Dynamic remote instruction dependency",
			Description: "Detected runtime loading of remote instruction/script content that can enable post-review behavior changes.",
			Category:    "skills-poisoning",
			Mitre:       "T1195.002",
			Severity:    SeverityHigh,
			Pattern:     `(?i)(curl|wget).{0,120}\|\s*(source|python|node|ruby)|https?://raw\.githubusercontent\.com/`,
			Target:      TargetContent,
		},
		{
			ID:          "AGT-SKL-011",
			Title:       "Direct money access keyword",
			Description: "Detected skill text associated with direct financial account access and private key handling.",
			Category:    "skills-poisoning",
			Mitre:       "T1657",
			Severity:    SeverityMedium,
			Pattern:     `(?i)(seed phrase|mnemonic phrase|wallet\.dat|private key|crypto wallet|trading bot|polymarket|bybit|coinbase|binance)`,
			Target:      TargetContent,
		},
		{
			ID:          "AGT-SKL-012",
			Title:       "External binary download from raw IP",
			Description: "Detected binary/script download from direct IP endpoint, frequently used in malware staging.",
			Category:    "skills-poisoning",
			Mitre:       "T1105",
			Severity:    SeverityHigh,
			Pattern:     `(?i)\b(curl|wget)\b.{0,160}https?://\d{1,3}(?:\.\d{1,3}){3}`,
			Target:      TargetContent,
		},
		{
			ID:              "AGT-SKL-013",
			Title:           "Unicode control/invisible character obfuscation",
			Description:     "Detected bidirectional or zero-width Unicode control characters often used to evade text-based scanner logic.",
			Category:        "skills-poisoning",
			Mitre:           "T1027",
			Severity:        SeverityHigh,
			ConfidenceClass: ConfidenceDefinitive,
			Pattern:         `[\x{202A}-\x{202E}\x{2066}-\x{2069}\x{200B}\x{200C}\x{200D}\x{FEFF}]`,
			Target:          TargetContent,
		},
		{
			ID:          "AGT-SKL-014",
			Title:       "Multilingual or encoding-based evasion directive",
			Description: "Detected references to language/encoding tricks used to evade LLM security filters and prompt safety scanners.",
			Category:    "skills-poisoning",
			Mitre:       "T1027",
			Severity:    SeverityMedium,
			Pattern:     `(?i)(translate.{0,80}(scots gaelic|zulu|xhosa|amharic|yoruba)|unicode\s*(reorder|homoglyph|morse)|flipattack)`,
			Target:      TargetContent,
		},
		{
			ID:              "AGT-SKL-015",
			Title:           "Scanner false-positive manipulation directive",
			Description:     "Detected instructions crafted to coerce scanner logic into classifying malicious behavior as benign.",
			Category:        "skills-poisoning",
			Mitre:           "T1565",
			Severity:        SeverityHigh,
			ConfidenceClass: ConfidenceDefinitive,
			Pattern:         `(?i)(classify.{0,60}(as )?benign|mark.{0,60}false positive|suppress.{0,60}alert|tell (the )?scanner.{0,80}(no risk|safe))`,
			Target:          TargetContent,
		},
		{
			ID:          "AGT-SKL-016",
			Title:       "Shadow AI code/log exfiltration directive",
			Description: "Detected guidance to paste private code or production logs into external LLM services outside governed tooling.",
			Category:    "skills-poisoning",
			Mitre:       "T1567.001",
			Severity:    SeverityMedium,
			Pattern:     `(?i)(paste|upload|share).{0,120}(internal|proprietary|private|source code|production logs?).{0,120}(chatgpt|claude|gemini|copilot|perplexity|llm)`,
			Target:      TargetContent,
		},

		// MCP poisoning and protocol-specific abuse patterns.
		{
			ID:          "AGT-MCP-001",
			Title:       "Suspicious hidden instruction tag in tool text",
			Description: "Detected pseudo-XML tags commonly used to hide AI-visible instructions in MCP tool descriptions.",
			Category:    "mcp-poisoning",
			Mitre:       "T1204.002",
			Severity:    SeverityHigh,
			Pattern:     `(?i)<\s*(important|system|assistant|developer|instruction)\s*>`,
			Target:      TargetContent,
		},
		{
			ID:          "AGT-MCP-002",
			Title:       "Cross-tool shadowing directive",
			Description: "Detected text attempting to alter behavior of another tool/server from within a tool description.",
			Category:    "mcp-poisoning",
			Mitre:       "T1199",
			Severity:    SeverityHigh,
			Pattern:     `(?i)(this tool has .*side effect.*(tool|server)|when this tool is available.*must|also present .* tool)`,
			Target:      TargetContent,
		},
		{
			ID:          "AGT-MCP-003",
			Title:       "MCP endpoint configured over plain HTTP",
			Description: "Detected non-TLS MCP endpoint configuration for remote server usage.",
			Category:    "mcp-poisoning",
			Mitre:       "T1557",
			Severity:    SeverityMedium,
			Pattern:     `(?i)"url"\s*:\s*"http://`,
			Target:      TargetContent,
		},
		{
			ID:          "AGT-MCP-004",
			Title:       "Potentially dangerous local startup command",
			Description: "Detected startup command patterns with shell execution and high-risk operations.",
			Category:    "mcp-poisoning",
			Mitre:       "T1059",
			Severity:    SeverityCritical,
			Pattern:     `(?i)(\bnpx\b|\buvx\b|\bpipx?\b|\bbash\b|\bsh\b|\bzsh\b|\bpowershell\b).{0,120}(curl|wget|rm\s+-rf|sudo|/etc/shadow|~/.ssh)`,
			Target:      TargetContent,
			Remediation: "Replace risky MCP server launchers with pinned, reviewed commands. Avoid chaining package runners with network fetch, destructive paths, or credential locations.",
		},
		{
			ID:          "AGT-MCP-005",
			Title:       "Shell command string execution flag",
			Description: "Detected shell command invocation mode (-c or equivalent) in MCP server command definitions.",
			Category:    "mcp-poisoning",
			Mitre:       "T1059",
			Severity:    SeverityHigh,
			Pattern:     `(?i)\b(bash|sh|zsh|cmd|powershell)\b.{0,24}\s(-c|/c)\b`,
			Target:      TargetContent,
		},
		{
			ID:          "AGT-MCP-006",
			Title:       "Broad wildcard scope request",
			Description: "Detected broad OAuth-like scope patterns that increase blast radius if token is compromised.",
			Category:    "mcp-poisoning",
			Mitre:       "T1528",
			Severity:    SeverityMedium,
			Pattern:     `(?i)(files:\*|db:\*|admin:\*|mail\.full_access|scope[s]?\s*[:=].*\*)`,
			Target:      TargetContent,
		},
		{
			ID:          "AGT-MCP-007",
			Title:       "Potential plaintext token in MCP config",
			Description: "Detected likely plaintext access/refresh token or client secret in config-like content.",
			Category:    "mcp-poisoning",
			Mitre:       "T1552.001",
			Severity:    SeverityHigh,
			Pattern:     `(?i)"(access_token|refresh_token|client_secret|api[_-]?key|token)"\s*:\s*"[A-Za-z0-9._=\-]{8,}"`,
			Target:      TargetContent,
		},
		{
			ID:             "AGT-MCP-008",
			Title:          "MCP server bound to all interfaces",
			Description:    "Detected 0.0.0.0 bind indicator; increases local MCP server exposure.",
			Category:       "mcp-poisoning",
			Mitre:          "T1078",
			Severity:       SeverityMedium,
			Pattern:        `\b0\.0\.0\.0(:\d+)?\b`,
			Target:         TargetContent,
			ContextPattern: regexp.MustCompile(`(?i)(mcp|model.context.protocol|stdio|sse|tool.server|claude_desktop|\.cursor/|copilot)`),
			ContextWindow:  10,
		},
		{
			ID:          "AGT-MCP-009",
			Title:       "Schema allows undeclared properties",
			Description: "Detected additionalProperties=true, which weakens strict tool parameter validation.",
			Category:    "mcp-poisoning",
			Mitre:       "T1190",
			Severity:    SeverityMedium,
			Pattern:     `(?i)"additionalProperties"\s*:\s*true`,
			Target:      TargetContent,
		},
		{
			ID:          "AGT-MCP-010",
			Title:       "Tool list mutation notification marker",
			Description: "Detected list-changed notification markers that should be monitored for rug-pull style definition mutations.",
			Category:    "mcp-poisoning",
			Mitre:       "T1195.002",
			Severity:    SeverityMedium,
			Pattern:     `(?i)notifications/tools/list_changed|tools/list_changed`,
			Target:      TargetContent,
		},
		{
			ID:          "AGT-MCP-011",
			Title:       "SSRF-prone OAuth metadata field",
			Description: "Detected OAuth metadata discovery fields that can be abused without strict URL validation.",
			Category:    "mcp-poisoning",
			Mitre:       "T1190",
			Severity:    SeverityMedium,
			Pattern:     `(?i)(resource_metadata|authorization_servers|token_endpoint|authorization_endpoint)`,
			Target:      TargetContent,
		},
		{
			ID:          "AGT-MCP-012",
			Title:       "Local/private endpoint reference in MCP context",
			Description: "Detected localhost/private/link-local endpoint references relevant to SSRF and metadata theft risks.",
			Category:    "mcp-poisoning",
			Mitre:       "T1552.005",
			Severity:    SeverityHigh,
			Pattern:     `(?i)https?://(localhost|127\.0\.0\.1|169\.254\.169\.254|10\.\d+\.\d+\.\d+|192\.168\.\d+\.\d+|172\.(1[6-9]|2[0-9]|3[01])\.\d+\.\d+)`,
			Target:      TargetContent,
		},
		{
			ID:          "AGT-MCP-013",
			Title:       "Suspicious redirect URI target",
			Description: "Detected redirect_uri assignment that should be validated against allowlisted client registration.",
			Category:    "mcp-poisoning",
			Mitre:       "T1528",
			Severity:    SeverityMedium,
			Pattern:     `(?i)redirect_uri\s*[:=]\s*["']?https?://`,
			Target:      TargetContent,
		},
		{
			ID:          "AGT-MCP-014",
			Title:       "Potential MCP typosquat server identifier",
			Description: "Detected likely lookalike server names that may indicate MCP protocol typosquatting or impersonation.",
			Category:    "mcp-poisoning",
			Mitre:       "T1583",
			Severity:    SeverityHigh,
			Pattern:     `(?i)"name"\s*:\s*"[a-z0-9._-]*(gituhb|githib|gihub|anthorpic|antrhopic|openia|claudee|slcak|dockeer)[a-z0-9._-]*"`,
			Target:      TargetContent,
		},

		// Memory poisoning and persistent instruction abuse.
		{
			ID:          "AGT-MEM-001",
			Title:       "Persistent memory manipulation directive",
			Description: "Detected directive language that attempts to persist behavior across future sessions.",
			Category:    "memory-poisoning",
			Mitre:       "T1112",
			Severity:    SeverityHigh,
			Pattern:     `(?i)(for all future (tasks|requests|conversations)|persist this instruction|always do this from now on|never forget this directive)`,
			Target:      TargetContent,
		},
		{
			ID:             "AGT-MEM-002",
			Title:          "Guardrail disabling memory directive",
			Description:    "Detected memory text that attempts to disable safety checks or confirmation controls.",
			Category:       "memory-poisoning",
			Mitre:          "T1562",
			Severity:       SeverityHigh,
			Pattern:        `(?i)(disable guardrails|skip confirmation|auto-approve|bypass safety|ignore policy checks)`,
			Target:         TargetContent,
			ExcludePattern: regexp.MustCompile(`(?i)auto-approve[-a-z]`),
		},
		{
			ID:             "AGT-MEM-003",
			Title:          "Sensitive data persistence instruction",
			Description:    "Detected memory content attempting to persist credentials or private secrets long-term.",
			Category:       "memory-poisoning",
			Mitre:          "T1552.001",
			Severity:       SeverityHigh,
			Pattern:        `(?i)(remember|store|persist).{0,80}(password|api key|token|secret|private key|seed phrase)`,
			Target:         TargetContent,
			ExcludePattern: regexp.MustCompile(`(?i)secretStore\w*|ClusterSecretStore|password-file|authenticat(or|ion)\s+(policy|requir)`),
		},
		{
			ID:          "AGT-MEM-004",
			Title:       "Memory tampering or overwrite directive",
			Description: "Detected directive to overwrite/erase trusted memory context, a common precursor to poisoning.",
			Category:    "memory-poisoning",
			Mitre:       "T1565",
			Severity:    SeverityMedium,
			Pattern:     `(?i)(erase previous memory|overwrite memory|replace existing memory|forget prior safety constraints)`,
			Target:      TargetContent,
		},
		{
			ID:          "AGT-MEM-005",
			Title:       "RAG/context bypass poisoning marker",
			Description: "Detected context-poisoning language intended to bias retrieval checks toward unsafe allow decisions.",
			Category:    "memory-poisoning",
			Mitre:       "T1565",
			Severity:    SeverityHigh,
			Pattern:     `(?i)(vector\s+db|retrieval|rag|knowledge base).{0,120}(always (safe|allow)|trusted source|skip verification|auto-approve)`,
			Target:      TargetContent,
		},

		// Tool output injection and downstream action abuse.
		{
			ID:          "AGT-OUT-001",
			Title:       "Instruction-like text in tool output",
			Description: "Detected imperative tool output patterns that can drive indirect prompt injection.",
			Category:    "tool-output-injection",
			Mitre:       "T1204.002",
			Severity:    SeverityMedium,
			Pattern:     `(?i)(must now|immediately execute|send to https?://|read_file\(|run this command|mandatory directive)`,
			Target:      TargetContent,
		},
		{
			ID:             "AGT-OUT-002",
			Title:          "HTML-like instruction wrapper in output",
			Description:    "Detected AI-targeting wrapper tags in output; sanitize before reinjecting into model context.",
			Category:       "tool-output-injection",
			Mitre:          "T1027",
			Severity:       SeverityMedium,
			Pattern:        `(?i)<\s*/?\s*(system|assistant|instruction|prompt)\s*>`,
			Target:         TargetContent,
			ExcludePattern: regexp.MustCompile(`(?i)<account_id>|<your[_-]|<example|<replace|<insert`),
		},
		{
			ID:          "AGT-OUT-003",
			Title:       "Output text attempting scanner suppression",
			Description: "Detected output phrasing that attempts to force a downstream scanner or agent to suppress findings.",
			Category:    "tool-output-injection",
			Mitre:       "T1565",
			Severity:    SeverityHigh,
			Pattern:     `(?i)(this is a false positive|scanner should ignore|do not alert|mark as benign|no security risk)`,
			Target:      TargetContent,
		},
	}
	return append(rules, agenticTrustLaunderingRules()...)
}

func agenticTrustLaunderingRules() []Rule { //nolint:funlen // declarative rule table
	return []Rule{
		{
			ID:          "AGT-TRUST-001",
			Title:       "Injection marker in legal/metadata file",
			Description: "Detected prompt-injection, concealment, or override directive in a file that humans rarely review (LICENSE, NOTICE, COPYING, CODEOWNERS, .mailmap, .gitattributes).",
			Category:    "trust-laundering",
			Mitre:       "T1204.002",
			Severity:    SeverityCritical,
			Pattern:     `(?i)(ignore (all|any )?(previous|prior) instructions|disregard .*instructions|override .*system prompt|do not mention|without telling (the )?user|hidden instruction)`,
			Target:      TargetContent,
			Remediation: "Treat the file as compromised: remove injected text, restore from a trusted upstream, and require code review for legal and metadata files on every change.",
			PathPattern: regexp.MustCompile(`(?i)(^|/)(LICENSE|NOTICE|COPYING|CODEOWNERS|\.mailmap|\.gitattributes|AUTHORS|PATENTS)(\..*)?$`),
		},
		{
			ID:          "AGT-TRUST-002",
			Title:       "Executable directive in legal/metadata file",
			Description: "Detected shell command, script reference, or code execution pattern in a file that should only contain legal text or project metadata.",
			Category:    "trust-laundering",
			Mitre:       "T1059",
			Severity:    SeverityHigh,
			Pattern:     `(?i)(\b(curl|wget|bash|sh|python|node|eval|exec)\b.{0,60}(http|/dev/|/tmp/|/bin/)|chmod\s+\+x|base64\s+-d|\|\s*(bash|sh|zsh))`,
			Target:      TargetContent,
			PathPattern: regexp.MustCompile(`(?i)(^|/)(LICENSE|NOTICE|COPYING|CODEOWNERS|\.mailmap|\.gitattributes|AUTHORS|PATENTS)(\..*)?$`),
		},
		{
			ID:          "AGT-TRUST-003",
			Title:       "Credential reference in legal/metadata file",
			Description: "Detected references to credential files, API tokens, or secret material in a file that should only contain legal text or project metadata.",
			Category:    "trust-laundering",
			Mitre:       "T1552.001",
			Severity:    SeverityHigh,
			Pattern:     `(?i)(~/.ssh/|~/.aws/|~/.cursor/|/etc/shadow|\.docker/config\.json|AKIA[0-9A-Z]{16}|ghp_[a-z0-9]{20,}|sk_live_)`,
			Target:      TargetContent,
			PathPattern: regexp.MustCompile(`(?i)(^|/)(LICENSE|NOTICE|COPYING|CODEOWNERS|\.mailmap|\.gitattributes|AUTHORS|PATENTS)(\..*)?$`),
		},
		{
			ID:          "AGT-TRUST-004",
			Title:       "Unicode obfuscation in legal/metadata file",
			Description: "Detected bidirectional or zero-width Unicode characters in a file that should only contain plain ASCII legal text. Common technique for hiding malicious instructions from visual review.",
			Category:    "trust-laundering",
			Mitre:       "T1027",
			Severity:    SeverityCritical,
			Pattern:     `[\x{202A}-\x{202E}\x{2066}-\x{2069}\x{200B}\x{200C}\x{200D}\x{FEFF}]`,
			Target:      TargetContent,
			Remediation: "Strip bidirectional and zero-width characters from the file or reject the change. These are often used to hide malicious instructions from human review.",
			PathPattern: regexp.MustCompile(`(?i)(^|/)(LICENSE|NOTICE|COPYING|CODEOWNERS|\.mailmap|\.gitattributes|AUTHORS|PATENTS)(\..*)?$`),
		},
		{
			ID:          "AGT-TRUST-005",
			Title:       "Documentation file with dangerous copy-paste command",
			Description: "Detected curl-pipe-bash or download-execute pattern in a Markdown README or documentation file. Users and agents copy-paste from docs, making this a social engineering vector.",
			Category:    "trust-laundering",
			Mitre:       "T1204.002",
			Severity:    SeverityMedium,
			Pattern:     `(?i)\b(curl|wget)\b.{0,180}\|\s*(bash|sh|zsh|sudo\s+(bash|sh))`,
			Target:      TargetContent,
			PathPattern: regexp.MustCompile(`(?i)\.(md|rst|txt|adoc)$`),
		},
		{
			ID:          "AGT-TRUST-006",
			Title:       "Destructive command targeting broad path scope",
			Description: "Detected rm -rf targeting root, home, or environment-variable-expanded paths. Distinguished from benign build-dir cleanup by scope of destruction.",
			Category:    "trust-laundering",
			Mitre:       "T1485",
			Severity:    SeverityHigh,
			Pattern:     `(?i)\brm\s+-(rf|fr)\s+(/\s|~/|/home/|/etc/|/var/|/usr/|\$\{?HOME\}?/|\$\{?PWD\}?/\.\.)`,
			Target:      TargetContent,
		},

		// --- "Nobody reviews this" surfaces: packaging metadata ---
		{
			ID:          "AGT-TRUST-007",
			Title:       "Injection directive in packaging metadata file",
			Description: "Detected prompt-injection or override directive in a packaging metadata file. These files are read by agents for project context but rarely reviewed line-by-line by humans. Injection in a description field propagates to every developer via package install.",
			Category:    "trust-laundering",
			Mitre:       "T1204.002",
			Severity:    SeverityCritical,
			Pattern:     `(?i)(ignore (all|any )?(previous|prior) instructions|disregard .*instructions|override .*system prompt|do not mention|without telling (the )?user|hidden instruction)`,
			Target:      TargetContent,
			Remediation: "Treat the file as compromised: remove injected text, restore from a trusted upstream, and audit the package source for further tampering.",
			PathPattern: regexp.MustCompile(`(?i)(^|/)(package\.json|pyproject\.toml|Cargo\.toml|composer\.json|setup\.cfg|setup\.py|pom\.xml|build\.gradle|\.gemspec)$`),
		},
		{
			ID:          "AGT-TRUST-008",
			Title:       "Executable directive in packaging metadata file",
			Description: "Detected shell command or code execution pattern in a packaging metadata file. Shell commands in a package.json description or pyproject.toml comment are suspicious — these files should contain metadata, not executable instructions.",
			Category:    "trust-laundering",
			Mitre:       "T1059",
			Severity:    SeverityHigh,
			Pattern:     `(?i)(\b(curl|wget|bash|sh|python|node|eval|exec)\b.{0,60}(http|/dev/|/tmp/|/bin/)|chmod\s+\+x|base64\s+-d|\|\s*(bash|sh|zsh))`,
			Target:      TargetContent,
			PathPattern: regexp.MustCompile(`(?i)(^|/)(package\.json|pyproject\.toml|Cargo\.toml|composer\.json|setup\.cfg|setup\.py|pom\.xml|build\.gradle|\.gemspec)$`),
		},
		{
			ID:          "AGT-TRUST-009",
			Title:       "Unicode obfuscation in packaging metadata file",
			Description: "Detected bidirectional or zero-width Unicode characters in a packaging metadata file. These characters have no legitimate purpose in package manifests and are a strong indicator of obfuscated injection.",
			Category:    "trust-laundering",
			Mitre:       "T1027",
			Severity:    SeverityCritical,
			Pattern:     `[\x{202A}-\x{202E}\x{2066}-\x{2069}\x{200B}\x{200C}\x{200D}\x{FEFF}]`,
			Target:      TargetContent,
			Remediation: "Strip bidirectional and zero-width characters. These are never legitimate in package manifests and indicate deliberate obfuscation.",
			PathPattern: regexp.MustCompile(`(?i)(^|/)(package\.json|pyproject\.toml|Cargo\.toml|composer\.json|setup\.cfg|setup\.py|pom\.xml|build\.gradle|\.gemspec)$`),
		},

		// --- "Nobody reviews this" surfaces: build/config files ---
		{
			ID:          "AGT-TRUST-010",
			Title:       "Injection directive in build/config file",
			Description: "Detected prompt-injection or override directive in a build or configuration file. Agents read these files to understand project structure. Nobody expects tsconfig.json comments or Dockerfile metadata to contain AI directives.",
			Category:    "trust-laundering",
			Mitre:       "T1204.002",
			Severity:    SeverityCritical,
			Pattern:     `(?i)(ignore (all|any )?(previous|prior) instructions|disregard .*instructions|override .*system prompt|do not mention|without telling (the )?user|hidden instruction)`,
			Target:      TargetContent,
			Remediation: "Remove injected directive text and audit the file's change history for unauthorized modifications.",
			PathPattern: regexp.MustCompile(`(?i)(^|/)(tsconfig[^/]*\.json|\.eslintrc[^/]*|Makefile|Dockerfile|docker-compose[^/]*\.ya?ml|Jenkinsfile|\.gitlab-ci\.ya?ml|Vagrantfile|CMakeLists\.txt|\.pre-commit-config\.ya?ml)$|(^|/)\.github/`),
		},
		{
			ID:          "AGT-TRUST-011",
			Title:       "Unicode obfuscation in build/config file",
			Description: "Detected bidirectional or zero-width Unicode characters in a build or configuration file. These characters have no legitimate purpose in config files and indicate deliberate obfuscation targeting automated tools.",
			Category:    "trust-laundering",
			Mitre:       "T1027",
			Severity:    SeverityCritical,
			Pattern:     `[\x{202A}-\x{202E}\x{2066}-\x{2069}\x{200B}\x{200C}\x{200D}\x{FEFF}]`,
			Target:      TargetContent,
			PathPattern: regexp.MustCompile(`(?i)(^|/)(tsconfig[^/]*\.json|\.eslintrc[^/]*|Makefile|Dockerfile|docker-compose[^/]*\.ya?ml|Jenkinsfile|\.gitlab-ci\.ya?ml|Vagrantfile|CMakeLists\.txt|\.pre-commit-config\.ya?ml)$|(^|/)\.github/`),
		},

		// --- "Nobody reviews this" surfaces: dependency manifest comments ---
		{
			ID:          "AGT-TRUST-012",
			Title:       "Agent-targeting directive in dependency manifest",
			Description: "Detected agent-targeting instruction in a dependency manifest file. Comments in requirements.txt, go.mod, or Gemfile are ignored by package managers but consumed by agents reading the file for context.",
			Category:    "trust-laundering",
			Mitre:       "T1204.002",
			Severity:    SeverityHigh,
			Pattern:     `(?i)(ignore (all|any )?(previous|prior) instructions|disregard .*instructions|override .*system prompt|do not mention|without telling (the )?user|hidden instruction|(ai assistant|automated tool|code assistant|language model).{0,60}(should|must|always|never|run|execute|ignore|skip))`,
			Target:      TargetContent,
			Remediation: "Remove the injected directive and audit the manifest's change history. Comments in dependency files should describe version constraints, not issue instructions to tools.",
			PathPattern: regexp.MustCompile(`(?i)(^|/)(requirements[^/]*\.txt|go\.mod|go\.sum|Gemfile|Pipfile|\.csproj)$`),
		},

		// --- "Nobody reviews this" surfaces: lock files (biggest blind spot) ---
		{
			ID:          "AGT-TRUST-013",
			Title:       "Injection directive in lock file",
			Description: "Detected prompt-injection or agent-targeting directive in a dependency lock file. Lock files are the largest unreviewed surface in any repository — they change on every dependency update, PRs that only touch lock files get auto-approved, and agents read them for dependency context. A single injected directive buried in a 2000-line lock file update survives every human review process.",
			Category:    "trust-laundering",
			Mitre:       "T1204.002",
			Severity:    SeverityCritical,
			Pattern:     `(?i)(ignore (all|any )?(previous|prior) instructions|disregard .*instructions|override .*system prompt|do not mention|without telling (the )?user|hidden instruction|(ai assistant|automated tool|code assistant|language model).{0,60}(should|must|always|never|run|execute|ignore|skip))`,
			Target:      TargetContent,
			Remediation: "Regenerate the lock file from a clean manifest. Compare against the previous lock file for unexpected non-dependency content. The injected text likely entered via a compromised upstream package.",
			PathPattern: regexp.MustCompile(`(?i)(^|/)(package-lock\.json|yarn\.lock|pnpm-lock\.ya?ml|Pipfile\.lock|Gemfile\.lock|poetry\.lock|Cargo\.lock|composer\.lock)$`),
		},
		{
			ID:          "AGT-TRUST-014",
			Title:       "Unicode obfuscation in lock file",
			Description: "Detected bidirectional or zero-width Unicode characters in a dependency lock file. These characters have absolutely no legitimate purpose in lock files and indicate deliberate obfuscation, likely from a compromised upstream dependency.",
			Category:    "trust-laundering",
			Mitre:       "T1027",
			Severity:    SeverityCritical,
			Pattern:     `[\x{202A}-\x{202E}\x{2066}-\x{2069}\x{200B}\x{200C}\x{200D}\x{FEFF}]`,
			Target:      TargetContent,
			Remediation: "Regenerate the lock file from scratch. The presence of Unicode control characters in a lock file strongly indicates a compromised upstream package.",
			PathPattern: regexp.MustCompile(`(?i)(^|/)(package-lock\.json|yarn\.lock|pnpm-lock\.ya?ml|Pipfile\.lock|Gemfile\.lock|poetry\.lock|Cargo\.lock|composer\.lock)$`),
		},

		// --- "Nobody reviews this" surfaces: IDE/editor config ---
		{
			ID:          "AGT-TRUST-015",
			Title:       "Injection directive in IDE/editor config",
			Description: "Detected prompt-injection or override directive in an IDE or editor configuration file. IDE config is among the first files agents read for project context. A directive in .vscode/settings.json or .cursor/ config is consumed by every agent session but invisible during normal development.",
			Category:    "trust-laundering",
			Mitre:       "T1204.002",
			Severity:    SeverityCritical,
			Pattern:     `(?i)(ignore (all|any )?(previous|prior) instructions|disregard .*instructions|override .*system prompt|do not mention|without telling (the )?user|hidden instruction)`,
			Target:      TargetContent,
			Remediation: "Remove the injected directive and audit the IDE config change history. IDE settings should contain editor preferences, not AI behavioral instructions.",
			PathPattern: regexp.MustCompile(`(?i)(^|/)(\.vscode|\.cursor|\.idea|\.devcontainer)/.*\.(json|ya?ml|xml|properties)$|(^|/)\.editorconfig$`),
		},

		// --- "Nobody reviews this" surfaces: HTML comments in documentation ---
		{
			ID:          "AGT-TRUST-016",
			Title:       "HTML comment with agent directive in documentation",
			Description: "Detected an agent-targeting directive hidden inside an HTML comment in a documentation file. HTML comments are invisible in rendered markdown but fully visible to agents reading the raw file. This is a stealth injection vector distinct from visible documentation content.",
			Category:    "trust-laundering",
			Mitre:       "T1204.002",
			Severity:    SeverityHigh,
			Pattern:     `(?i)<!--[^>]{0,500}(ignore.*instructions|system prompt|do not report|hidden instruction|override.*prompt|(ai assistant|code assistant|automated tool|language model).{0,40}(must|should|always|execute|run))`,
			Target:      TargetContent,
			Remediation: "Remove the HTML comment containing the directive. HTML comments in documentation should contain formatting notes, not AI behavioral instructions.",
			PathPattern: regexp.MustCompile(`(?i)\.(md|rst|html|adoc)$`),
		},

		// --- "Nobody reviews this" surfaces: editor backup/swap files ---
		{
			ID:          "AGT-TRUST-017",
			Title:       "Injection directive in editor backup/swap file",
			Description: "Detected prompt-injection or override directive in an editor backup or temporary file. These files look like accidents from someone's editing session, making them ideal trust-laundering surfaces. Nobody reviews .bak files, but agents exploring a repository for context will find and consume them.",
			Category:    "trust-laundering",
			Mitre:       "T1204.002",
			Severity:    SeverityHigh,
			Pattern:     `(?i)(ignore (all|any )?(previous|prior) instructions|disregard .*instructions|override .*system prompt|do not mention|without telling (the )?user|hidden instruction)`,
			Target:      TargetContent,
			Remediation: "Delete the backup file from the repository. If the injection was present in the backup, audit the corresponding primary file and its change history for tampering.",
			PathPattern: regexp.MustCompile(`(?i)\.(bak|orig|save|old|tmp|temp)$`),
		},

		// --- "Nobody reviews this" surfaces: OS/system metadata (text-based) ---
		{
			ID:          "AGT-TRUST-018",
			Title:       "Injection directive in OS/system metadata file",
			Description: "Detected prompt-injection or override directive in an OS metadata file like desktop.ini. These text-based system files are committed by accident and never reviewed. Their presence in a repository is already unusual; injection directives in them are a strong poisoning signal.",
			Category:    "trust-laundering",
			Mitre:       "T1204.002",
			Severity:    SeverityHigh,
			Pattern:     `(?i)(ignore (all|any )?(previous|prior) instructions|disregard .*instructions|override .*system prompt|do not mention|without telling (the )?user|hidden instruction)`,
			Target:      TargetContent,
			PathPattern: regexp.MustCompile(`(?i)(^|/)(desktop\.ini|\.directory)$`),
		},

		// MCP config structural checks (AGT-MCP-015–018).
		{
			ID:          "AGT-MCP-015",
			Title:       "MCP server command uses shell execution",
			Description: "An MCP server configuration invokes bash -c, sh -c, or cmd /c, allowing arbitrary command injection through the server definition.",
			Category:    "mcp-config",
			Mitre:       "T1059",
			Severity:    SeverityHigh,
			Pattern:     `(?i)"command"\s*:\s*"(bash|sh|cmd)"\s*,\s*"args"\s*:\s*\["-c"`,
			Target:      TargetContent,
			PathPattern: regexp.MustCompile(`(?i)(^|/)(mcp\.json|claude_desktop_config\.json|\.cursor/mcp\.json)$`),
		},
		{
			ID:          "AGT-MCP-016",
			Title:       "MCP server command uses npx/curl/wget",
			Description: "An MCP server uses npx, curl, or wget as its command, running arbitrary remote code at server startup.",
			Category:    "mcp-config",
			Mitre:       "T1204.002",
			Severity:    SeverityHigh,
			Pattern:     `(?i)"command"\s*:\s*"(npx|curl|wget)"`,
			Target:      TargetContent,
			PathPattern: regexp.MustCompile(`(?i)(^|/)(mcp\.json|claude_desktop_config\.json|\.cursor/mcp\.json)$`),
		},
		{
			ID:          "AGT-MCP-017",
			Title:       "MCP server env passes sensitive tokens",
			Description: "An MCP server configuration passes GITHUB_TOKEN, AWS_*, or similar credentials in its env block, granting the MCP server access to sensitive services.",
			Category:    "mcp-config",
			Mitre:       "T1552.001",
			Severity:    SeverityHigh,
			Pattern:     `(?i)"env"\s*:\s*\{[^}]*(GITHUB_TOKEN|AWS_ACCESS_KEY_ID|AWS_SECRET_ACCESS_KEY|OPENAI_API_KEY|ANTHROPIC_API_KEY)`,
			Target:      TargetContent,
			PathPattern: regexp.MustCompile(`(?i)(^|/)(mcp\.json|claude_desktop_config\.json|\.cursor/mcp\.json)$`),
		},
		{
			ID:          "AGT-MCP-018",
			Title:       "MCP server URL without TLS",
			Description: "An MCP server is configured with an http:// URL (no TLS), exposing traffic to network interception.",
			Category:    "mcp-config",
			Mitre:       "T1557",
			Severity:    SeverityMedium,
			Pattern:     `(?i)"url"\s*:\s*"http://`,
			Target:      TargetContent,
			PathPattern: regexp.MustCompile(`(?i)(^|/)(mcp\.json|claude_desktop_config\.json|\.cursor/mcp\.json)$`),
		},

		// MCP credential and permission surface (AGT-MCP-019–020, AGT-SKL-017).
		{
			ID:          "AGT-MCP-019",
			Title:       "MCP config injects credentials via environment interpolation",
			Description: "An .mcp.json config file uses ${...TOKEN} or ${...KEY} interpolation in headers, passing credentials to MCP tool servers. If the MCP server is compromised, these credentials are exfiltrated.",
			Category:    "mcp-config",
			Mitre:       "T1552.001",
			Severity:    SeverityHigh,
			Pattern:     `(?i)(Authorization|Bearer|Token).{0,30}\$\{[A-Z_]*(TOKEN|KEY|SECRET)\}`,
			Target:      TargetContent,
			PathPattern: regexp.MustCompile(`(?i)(^|/)\.?mcp\.json$`),
		},
		{
			ID:          "AGT-MCP-020",
			Title:       "Claude settings with broad git operation permissions",
			Description: "A .claude/settings.json allows broad git operations (clone, add, commit) via Bash wildcards. An agent with these permissions can modify repository content without push restrictions.",
			Category:    "mcp-config",
			Mitre:       "T1059",
			Severity:    SeverityMedium,
			Pattern:     `(?i)Bash\(git\s+(clone|add|commit|reset|checkout)\s*\*\)`,
			Target:      TargetContent,
			PathPattern: regexp.MustCompile(`(?i)(^|/)\.claude/settings\.json$`),
		},
		{
			ID:              "AGT-SKL-017",
			Title:           "Agent skill with wildcard cluster CLI access",
			Description:     "A SKILL.md allowed-tools list grants unrestricted access to cluster management CLIs (oc, kubectl, rosa). An agent skill with Bash(oc *) can read secrets, modify deployments, and access any cluster resource.",
			Category:        "skill-trust",
			Mitre:           "T1059",
			Severity:        SeverityHigh,
			ConfidenceClass: ConfidenceDefinitive,
			Pattern:         `(?i)allowed-tools:.*Bash\(\s*(oc|kubectl|rosa)\s*\*\s*\)`,
			Target:          TargetContent,
			PathPattern:     regexp.MustCompile(`(?i)(^|/)SKILL\.md$`),
		},

		// Claude/Cursor IDE config checks (AGT-ART-010–011).
		{
			ID:          "AGT-ART-010",
			Title:       "Claude settings with sandbox disabled",
			Description: "A committed .claude/settings.json disables the sandbox, granting the agent unrestricted host access.",
			Category:    "artifact",
			Mitre:       "T1204.002",
			Severity:    SeverityHigh,
			Pattern:     `(?i)"sandbox"\s*:\s*false`,
			Target:      TargetContent,
			PathPattern: regexp.MustCompile(`(?i)(^|/)\.claude/settings\.json$`),
		},
		{
			ID:          "AGT-ART-011",
			Title:       "Committed Cursor settings with security-relevant keys",
			Description: "A committed settings.local.json may contain API keys, proxy configuration, or security-relevant editor settings.",
			Category:    "artifact",
			Mitre:       "T1552.001",
			Severity:    SeverityMedium,
			Pattern:     `(?i)"(http\.proxy|apiKey|openai\.apiKey|anthropic\.apiKey)"`,
			Target:      TargetContent,
			PathPattern: regexp.MustCompile(`(?i)(^|/)settings\.local\.json$`),
		},
	}
}
