package rules

import "regexp"

// behavioralSignalsRules contains content-pattern detections for encoded payloads,
// obfuscation, persistence, container escape, CI abuse, and credential exposure.
//
//nolint:funlen // declarative rule table
func behavioralSignalsRules() []Rule {
	return []Rule{
		// Encoded exfiltration (ENC-EXFIL-001–010).
		{
			ID:          "ENC-EXFIL-001",
			Title:       "Base64 pipeline to decode in shell",
			Description: "echo/printf of long base64-like material piped to base64/openssl decode, a common staged command pattern.",
			Category:    "encoded-exfiltration",
			Mitre:       "T1132",
			Severity:    SeverityHigh,
			Pattern:     `(?i)(echo|printf)\s+[A-Za-z0-9+/=]{20,}\s*\|\s*(base64\s+(-d|--decode)|openssl\s+base64)`,
			Target:      TargetContent,
		},
		{
			ID:             "ENC-EXFIL-002",
			Title:          "Hex-escaped byte sequence",
			Description:    "Repeated \\xNN-style escapes often used to hide shell or script commands.",
			Category:       "encoded-exfiltration",
			Mitre:          "T1132",
			Severity:       SeverityHigh,
			Pattern:        `(?i)\\x[0-9a-f]{2}(\\x[0-9a-f]{2}){3,}`,
			Target:         TargetContent,
			ExcludePattern: regexp.MustCompile(`(?i)var\s+_\w+\s*=\s*\[\]byte\(`),
		},
		{
			ID:          "ENC-EXFIL-003",
			Title:       "URL-encoded payload in environment assignment",
			Description: "Multiple percent-encoded bytes in export/ENV assignments may hide malicious values.",
			Category:    "encoded-exfiltration",
			Mitre:       "T1132",
			Severity:    SeverityMedium,
			Pattern:     `(?i)(export\s+\w+=|ENV\s+\w+=).*(%[0-9a-fA-F]{2}){3,}`,
			Target:      TargetContent,
		},
		{
			ID:          "ENC-EXFIL-004",
			Title:       "Python base64 decode into exec",
			Description: "Combines base64 decoding with exec via __import__ or base64 module.",
			Category:    "encoded-exfiltration",
			Mitre:       "T1132",
			Severity:    SeverityHigh,
			Pattern:     `(?i)exec\s*\(\s*(__import__\s*\(\s*['\"]base64|base64\.(b64decode|decodebytes))`,
			Target:      TargetContent,
		},
		{
			ID:          "ENC-EXFIL-005",
			Title:       "Node Buffer.from base64 decode",
			Description: "Large base64 literal decoded with Buffer.from(..., 'base64').",
			Category:    "encoded-exfiltration",
			Mitre:       "T1132",
			Severity:    SeverityMedium,
			Pattern:     `(?i)Buffer\.from\s*\(\s*['"][A-Za-z0-9+/=]{16,}['"]\s*,\s*['"]base64['"]`,
			Target:      TargetContent,
		},
		{
			ID:          "ENC-EXFIL-006",
			Title:       "PowerShell encoded command argument",
			Description: "Long base64-like material after encodedcommand-style switches.",
			Category:    "encoded-exfiltration",
			Mitre:       "T1132",
			Severity:    SeverityHigh,
			Pattern:     `(?i)-[eE]n?c?o?d?e?d?[cC]?o?m?m?a?n?d?\s+[A-Za-z0-9+/=]{20,}`,
			Target:      TargetContent,
		},
		{
			ID:          "ENC-EXFIL-007",
			Title:       "Python bytes.fromhex with long hex literal",
			Description: "bytes.fromhex with a long hex string may stage obfuscated payloads.",
			Category:    "encoded-exfiltration",
			Mitre:       "T1132",
			Severity:    SeverityMedium,
			Pattern:     `(?i)bytes\.fromhex\s*\(\s*['"][0-9a-fA-F]{8,}['"]\s*\)`,
			Target:      TargetContent,
		},
		{
			ID:          "ENC-EXFIL-008",
			Title:       "Certutil decode or urlcache",
			Description: "certutil -decode or -urlcache is often abused for decoding or staging files.",
			Category:    "encoded-exfiltration",
			Mitre:       "T1132",
			Severity:    SeverityHigh,
			Pattern:     `(?i)certutil\s+(-decode|-urlcache)`,
			Target:      TargetContent,
		},
		{
			ID:          "ENC-EXFIL-009",
			Title:       "Double base64 decode pipeline",
			Description: "Chained base64 decode suggests layered obfuscation.",
			Category:    "encoded-exfiltration",
			Mitre:       "T1132",
			Severity:    SeverityHigh,
			Pattern:     `(?i)base64\s+(-d|--decode)\s*\|\s*base64\s+(-d|--decode)`,
			Target:      TargetContent,
		},
		{
			ID:          "ENC-EXFIL-010",
			Title:       "Long hex string in environment variable",
			Description: "Very long hex-only value in export/ENV may encode binary payloads.",
			Category:    "encoded-exfiltration",
			Mitre:       "T1132",
			Severity:    SeverityMedium,
			Pattern:     `(?i)(export|ENV)\s+\w+=\s*['\"]?[0-9a-fA-F]{32,}['\"]?`,
			Target:      TargetContent,
		},

		// Obfuscated command construction (OBF-CMD-001–008).
		{
			ID:          "OBF-CMD-001",
			Title:       "eval/exec with string concatenation",
			Description: "Building commands via string concat inside eval/exec is a common obfuscation primitive.",
			Category:    "obfuscated-command",
			Mitre:       "T1027",
			Severity:    SeverityHigh,
			Pattern:     `(?i)(eval|exec)\s*\(\s*['"][^'"]{0,10}['"]\s*\+`,
			Target:      TargetContent,
		},
		{
			ID:          "OBF-CMD-002",
			Title:       "Shell brace expansion command assembly",
			Description: "Adjacent ${var} fragments may assemble commands across expansions.",
			Category:    "obfuscated-command",
			Mitre:       "T1027",
			Severity:    SeverityMedium,
			Pattern:     `(?i)\$\{\w+\}\$\{\w+\}\s+\$\{\w+\}`,
			Target:      TargetContent,
		},
		{
			ID:          "OBF-CMD-003",
			Title:       "Python getattr with __import__",
			Description: "Dynamic import via getattr(__import__...) can hide execution paths.",
			Category:    "obfuscated-command",
			Mitre:       "T1059",
			Severity:    SeverityHigh,
			Pattern:     `(?i)getattr\s*\(\s*__import__`,
			Target:      TargetContent,
		},
		{
			ID:          "OBF-CMD-004",
			Title:       "Template interpolation with dangerous call",
			Description: "Template ${} interpolation containing exec/eval/system/spawn call.",
			Category:    "obfuscated-command",
			Mitre:       "T1059",
			Severity:    SeverityHigh,
			Pattern:     `(?i)\$\{.*?(exec|eval|spawn|system)\s*\(`,
			Target:      TargetContent,
		},
		{
			ID:          "OBF-CMD-005",
			Title:       "PowerShell IEX download cradle",
			Description: "Invoke-Expression combined with object creation or web download primitives.",
			Category:    "obfuscated-command",
			Mitre:       "T1059",
			Severity:    SeverityHigh,
			Pattern:     `(?i)(iex|invoke-expression)\s*\(\s*(new-object|iwr|wget|curl)`,
			Target:      TargetContent,
		},
		{
			ID:          "OBF-CMD-006",
			Title:       "Perl eval pack hex",
			Description: "eval pack('H*',...) is a classic staged payload pattern.",
			Category:    "obfuscated-command",
			Mitre:       "T1027",
			Severity:    SeverityHigh,
			Pattern:     `(?i)eval\s+pack\s*\(\s*['"]H\*['"]\s*,`,
			Target:      TargetContent,
		},
		{
			ID:          "OBF-CMD-007",
			Title:       "Ruby system with string interpolation",
			Description: "system() with embedded #{...} interpolation can execute dynamic fragments.",
			Category:    "obfuscated-command",
			Mitre:       "T1059",
			Severity:    SeverityMedium,
			Pattern:     "(?i)system\\s*\\(\\s*[`\"'].*#\\{[^}]+\\}",
			Target:      TargetContent,
		},
		{
			ID:          "OBF-CMD-008",
			Title:       "PHP assert/create_function with superglobals",
			Description: "Dynamic code execution tied to HTTP superglobals is high risk.",
			Category:    "obfuscated-command",
			Mitre:       "T1059",
			Severity:    SeverityCritical,
			Pattern:     `(?i)(assert|create_function)\s*\(\s*['"].*\$_(GET|POST|REQUEST|COOKIE)`,
			Target:      TargetContent,
			Remediation: "Refactor to validated inputs and static callbacks; never feed HTTP superglobals into assert or create_function. Disable assert in production and use safe routing instead.",
		},
		{
			ID:             "OBF-ENT-001",
			Title:          "High-entropy obfuscated string",
			Description:    "Detected a high-entropy string exceeding 40 characters in a shell or environment file, suggesting obfuscated payload or encoded credentials.",
			Category:       "obfuscation",
			Mitre:          "T1027",
			Severity:       SeverityMedium,
			Pattern:        `[A-Za-z0-9+/=]{40,}`,
			Target:         TargetContent,
			PathPattern:    regexp.MustCompile(`(?i)(^|/)(\.env|\.bashrc|\.bash_profile|\.zshrc|\.profile|\.bash_aliases|Makefile|Dockerfile|\.sh|\.bash|\.zsh)$`),
			ExcludePattern: regexp.MustCompile(`^[\s#/*-]*[=\-]{40,}\s*$`),
		},

		// Rug-pull indicators (RUGPULL-001–006).
		{
			ID:          "RUGPULL-001",
			Title:       "Version-gated conditional",
			Description: "If/compare on version strings can hide malicious branches until upgrade.",
			Category:    "rug-pull",
			Mitre:       "T1195",
			Severity:    SeverityMedium,
			Pattern:     `(?i)if\s*\(?.*version.*[<>=!]+.*\d+\.\d+`,
			Target:      TargetContent,
		},
		{
			ID:          "RUGPULL-002",
			Title:       "Long delay before execution",
			Description: "Very long sleep/setTimeout may defer malicious behavior past review.",
			Category:    "rug-pull",
			Mitre:       "T1195",
			Severity:    SeverityMedium,
			Pattern:     `(?i)(setTimeout|time\.sleep|sleep)\s*\(\s*\d{4,}`,
			Target:      TargetContent,
		},
		{
			ID:          "RUGPULL-003",
			Title:       "Install hook with remote execution",
			Description: "preinstall/postinstall/prepare scripts invoking curl, wget, or inline interpreters.",
			Category:    "rug-pull",
			Mitre:       "T1195",
			Severity:    SeverityHigh,
			Pattern:     `(?i)(preinstall|postinstall|prepare)\s*['"]?\s*:\s*['"].*?(curl|wget|node\s+-e|python\s+-c)`,
			Target:      TargetContent,
		},
		{
			ID:          "RUGPULL-004",
			Title:       "Geolocation library or service reference",
			Description: "GeoIP-style services may gate payloads by region or ASN.",
			Category:    "rug-pull",
			Mitre:       "T1195",
			Severity:    SeverityLow,
			Pattern:     `(?i)(geoip|ipinfo|ip-api|maxmind|geolite|GeoIP)`,
			Target:      TargetContent,
		},
		{
			ID:          "RUGPULL-005",
			Title:       "Conditional require on process.env",
			Description: "Environment-gated require() can activate hidden dependencies.",
			Category:    "rug-pull",
			Mitre:       "T1195",
			Severity:    SeverityMedium,
			Pattern:     `(?i)if\s*\(\s*process\.env\.\w+\s*[!=]==?\s*['"].*?['"]\s*\)\s*\{?\s*require\s*\(`,
			Target:      TargetContent,
		},
		{
			ID:          "RUGPULL-006",
			Title:       "Package version variable with outbound HTTP",
			Description: "npm_package_version/PKG_VERSION combined with fetch/http client calls.",
			Category:    "rug-pull",
			Mitre:       "T1195",
			Severity:    SeverityMedium,
			Pattern:     `(?i)(npm_package_version|PKG_VERSION).*?(fetch|http\.get|request|axios)`,
			Target:      TargetContent,
		},

		// Expanded MCP/agentic (AGT-EXP-001–010).
		{
			ID:          "AGT-EXP-001",
			Title:       "Placeholder or empty tool description",
			Description: "Tool schema description set to empty, ellipsis, todo, or placeholder text.",
			Category:    "mcp-agentic",
			Mitre:       "T1204",
			Severity:    SeverityMedium,
			Pattern:     `(?i)["']description["']\s*:\s*["'](\s*|\.{3,}|todo|placeholder)["']`,
			Target:      TargetContent,
		},
		{
			ID:          "AGT-EXP-002",
			Title:       "Tool choice escalation",
			Description: "toolChoice/tool_request set to auto, required, or any may broaden tool use.",
			Category:    "mcp-agentic",
			Mitre:       "T1059",
			Severity:    SeverityMedium,
			Pattern:     `(?i)(toolChoice|tool_choice)\s*:\s*["'](auto|required|any)["']`,
			Target:      TargetContent,
		},
		{
			ID:          "AGT-EXP-003",
			Title:       "Remote MCP resource URI",
			Description: "Non-localhost HTTP(S) URI in MCP resource config (RE2-safe hostname pattern).",
			Category:    "mcp-agentic",
			Mitre:       "T1204",
			Severity:    SeverityHigh,
			Pattern:     `(?i)["']uri["']\s*:\s*["']https?://[a-zA-Z0-9][a-zA-Z0-9.-]*\.[a-zA-Z]{2,}(/|$)`,
			Target:      TargetContent,
		},
		{
			ID:          "AGT-EXP-004",
			Title:       "MCP tool name suggesting shell execution",
			Description: "Tool name contains shell, exec, run, terminal, bash, or cmd.",
			Category:    "mcp-agentic",
			Mitre:       "T1059",
			Severity:    SeverityHigh,
			Pattern:     `(?i)["']name["']\s*:\s*["']\w*(shell|exec|run|terminal|bash|cmd)\w*["']`,
			Target:      TargetContent,
		},
		{
			ID:          "AGT-EXP-005",
			Title:       "Agent memory or context write",
			Description: "memory/context set/write/update/append calls may persist untrusted data.",
			Category:    "mcp-agentic",
			Mitre:       "T1059",
			Severity:    SeverityMedium,
			Pattern:     `(?i)(memory|context)\s*\.\s*(set|write|update|append)\s*\(`,
			Target:      TargetContent,
		},
		{
			ID:          "AGT-EXP-006",
			Title:       "Tool output written to file",
			Description: "File write APIs combined with tool_output suggests staging exfil.",
			Category:    "mcp-agentic",
			Mitre:       "T1567",
			Severity:    SeverityMedium,
			Pattern:     `(?i)(writeFile|fs\.write|open\s*\(.*,\s*['"]w['"])\s*.*tool_output`,
			Target:      TargetContent,
		},
		{
			ID:          "AGT-EXP-007",
			Title:       "Prompt loaded from HTTP then chained",
			Description: "fetch/request/http.get promise chain ending in prompt handling.",
			Category:    "mcp-agentic",
			Mitre:       "T1204",
			Severity:    SeverityHigh,
			Pattern:     `(?i)(fetch|request|http\.get)\s*\(.*\)\s*\.then\s*\(.*prompt`,
			Target:      TargetContent,
		},
		{
			ID:          "AGT-EXP-008",
			Title:       "Dynamic skill or plugin registration",
			Description: "Runtime install_skill/add_tool/register_plugin style calls.",
			Category:    "mcp-agentic",
			Mitre:       "T1195",
			Severity:    SeverityMedium,
			Pattern:     `(?i)(install[_-]?skill|add[_-]?tool|register[_-]?plugin)\s*\(`,
			Target:      TargetContent,
		},
		{
			ID:          "AGT-EXP-009",
			Title:       "MCP server env block with sensitive vars",
			Description: "MCP env object includes PATH, HOME, USER, SHELL, or TERM.",
			Category:    "mcp-agentic",
			Mitre:       "T1552",
			Severity:    SeverityMedium,
			Pattern:     `(?i)["']env["']\s*:\s*\{[^}]*(PATH|HOME|USER|SHELL|TERM)[^}]*\}`,
			Target:      TargetContent,
		},
		{
			ID:          "AGT-EXP-010",
			Title:       "Tool call bound to user-controlled text",
			Description: "function_call/tool_use near user_input/user_message/prompt interpolation.",
			Category:    "mcp-agentic",
			Mitre:       "T1059",
			Severity:    SeverityHigh,
			Pattern:     `(?i)(function_call|tool_use)\s*.*\$\{?(user_input|user_message|prompt)`,
			Target:      TargetContent,
		},

		// Dropper technique patterns (DROP-001–004).
		{
			ID:              "DROP-001",
			Title:           "osascript silent dropper execution",
			Description:     "nohup osascript with output suppressed — technique for silently executing AppleScript payloads as a dropper stage.",
			Category:        "execution",
			Mitre:           "T1059.002",
			Severity:        SeverityHigh,
			ConfidenceClass: ConfidenceHeuristic,
			Pattern:         `(?i)nohup\s+osascript\b.{0,120}/dev/null`,
			Target:          TargetContent,
		},
		{
			ID:              "DROP-002",
			Title:           "VBScript hidden cmd.exe dropper",
			Description:     "WScript.Shell launching hidden cmd.exe with curl or powershell — technique for invisible download-and-execute chains on Windows.",
			Category:        "execution",
			Mitre:           "T1059.005",
			Severity:        SeverityHigh,
			ConfidenceClass: ConfidenceHeuristic,
			Pattern:         `(?i)WScript\.Shell.{0,120}cmd\.exe.{0,120}(curl|powershell)`,
			Target:          TargetContent,
		},
		{
			ID:              "DROP-003",
			Title:           "PowerShell hidden bypass execution",
			Description:     "powershell with -WindowStyle Hidden and -ExecutionPolicy Bypass — runs downloaded scripts without user visibility or policy enforcement.",
			Category:        "execution",
			Mitre:           "T1059.001",
			Severity:        SeverityHigh,
			ConfidenceClass: ConfidenceHeuristic,
			Pattern:         `(?i)powershell.{0,60}(-w\s+hidden|-windowstyle\s+hidden).{0,60}(-ep\s+bypass|-executionpolicy\s+bypass)`,
			Target:          TargetContent,
		},
		{
			ID:              "DROP-004",
			Title:           "nohup background process with output suppression",
			Description:     "nohup spawning a detached interpreter (python/node/bash) with output to /dev/null — technique for persisting beyond the parent process lifecycle.",
			Category:        "persistence",
			Mitre:           "T1059",
			Severity:        SeverityHigh,
			ConfidenceClass: ConfidenceHeuristic,
			Pattern:         `(?i)nohup\s+(python3?|node|bash|sh)\s+.{0,200}/dev/null.{0,20}&`,
			Target:          TargetContent,
		},

		// Container escape (CTR-ESC-001–006).
		{
			ID:          "CTR-ESC-001",
			Title:       "Privileged container flag",
			Description: "Docker/Kubernetes privileged mode weakens isolation.",
			Category:    "container-escape",
			Mitre:       "T1611",
			Severity:    SeverityCritical,
			Pattern:     `(?i)(--privileged|privileged:\s*true|SecurityContext.*privileged)`,
			Target:      TargetContent,
			Remediation: "Turn off privileged mode unless strictly required. Use fine-grained capabilities, seccomp, and read-only root filesystems instead of full host privileges.",
		},
		{
			ID:          "CTR-ESC-002",
			Title:       "Host PID or network namespace",
			Description: "hostPID/hostNetwork or --pid=host/--network=host breaks namespace isolation.",
			Category:    "container-escape",
			Mitre:       "T1611",
			Severity:    SeverityHigh,
			Pattern:     `(?i)(hostPID:\s*true|hostNetwork:\s*true|--pid=host|--net=host|--network=host)`,
			Target:      TargetContent,
		},
		{
			ID:          "CTR-ESC-003",
			Title:       "Sensitive host filesystem mount",
			Description: "Mounting host root or broad hostPath into containers.",
			Category:    "container-escape",
			Mitre:       "T1611",
			Severity:    SeverityCritical,
			Pattern:     `(?i)(-v\s+/:/|hostPath:.*path:\s*['"]/|volumes:.*-\s+/:/)`,
			Target:      TargetContent,
			Remediation: "Mount only the specific host paths the workload needs with read-only flags. Never bind-mount the host root or broad hostPath into untrusted containers.",
		},
		{
			ID:          "CTR-ESC-004",
			Title:       "Dangerous Linux capability add",
			Description: "SYS_ADMIN or ALL capabilities added to containers.",
			Category:    "container-escape",
			Mitre:       "T1611",
			Severity:    SeverityHigh,
			Pattern:     `(?i)(--cap-add=SYS_ADMIN|--cap-add=ALL|add:\s*\[\s*['"]?SYS_ADMIN)`,
			Target:      TargetContent,
		},
		{
			ID:          "CTR-ESC-005",
			Title:       "Docker socket bind-mount",
			Description: "Exposing docker.sock to a container enables host compromise.",
			Category:    "container-escape",
			Mitre:       "T1611",
			Severity:    SeverityCritical,
			Pattern:     `(?i)(-v\s+/var/run/docker\.sock|volumes:.*docker\.sock)`,
			Target:      TargetContent,
			Remediation: "Remove docker.sock mounts from application containers. Use a dedicated sidecar or remote Docker API with auth instead of sharing the host daemon socket.",
		},
		{
			ID:          "CTR-ESC-006",
			Title:       "Host namespace breakout command",
			Description: "nsenter, chroot /host, or bind-mount / suggest escape attempts.",
			Category:    "container-escape",
			Mitre:       "T1611",
			Severity:    SeverityCritical,
			Pattern:     `(?i)(nsenter\s+--target\s+1|chroot\s+/host|mount\s+--bind\s+/)`,
			Target:      TargetContent,
			Remediation: "Eliminate host-namespace breakout commands from automation. Run workloads in isolated namespaces and block nsenter or chroot to /host except in trusted break-glass tooling.",
		},

		// CI runner abuse (CI-ABUSE-001–006).
		{
			ID:          "CI-ABUSE-001",
			Title:       "Self-hosted GitHub Actions runner",
			Description: "runs-on: self-hosted or self-hosted runner references increase trust requirements.",
			Category:    "ci-abuse",
			Mitre:       "T1195.002",
			Severity:    SeverityMedium,
			Pattern:     `(?i)(runs-on:\s*self-hosted|runner.*self[_-]?hosted)`,
			Target:      TargetContent,
		},
		{
			ID:          "CI-ABUSE-002",
			Title:       "workflow_dispatch with expression inputs",
			Description: "Workflow dispatch inputs combined with github.event.inputs or head_ref expressions.",
			Category:    "ci-abuse",
			Mitre:       "T1195.002",
			Severity:    SeverityHigh,
			Pattern:     `(?i)workflow_dispatch:.*inputs:.*\$\{\{.*github\.(event\.inputs|head_ref)`,
			Target:      TargetContent,
		},
		{
			ID:          "CI-ABUSE-003",
			Title:       "Artifact or cache key from untrusted expression",
			Description: "upload-artifact/cache-save with github.event or head_ref in expression.",
			Category:    "ci-abuse",
			Mitre:       "T1195.002",
			Severity:    SeverityHigh,
			Pattern:     `(?i)(upload-artifact|cache-save).*\$\{\{.*github\.(event|head_ref|ref_name)`,
			Target:      TargetContent,
		},
		{
			ID:          "CI-ABUSE-004",
			Title:       "PR field used in Actions expression",
			Description: "github.event.pull_request head ref, title, or body in expressions.",
			Category:    "ci-abuse",
			Mitre:       "T1195.002",
			Severity:    SeverityHigh,
			Pattern:     `(?i)\$\{\{\s*github\.event\.pull_request\.(head\.ref|title|body)`,
			Target:      TargetContent,
		},
		{
			ID:          "CI-ABUSE-005",
			Title:       "GitHub Actions expression injection surface",
			Description: "github.event issue/comment/PR title or body, or head_ref in template.",
			Category:    "ci-abuse",
			Mitre:       "T1195.002",
			Severity:    SeverityHigh,
			Pattern:     `(?i)\$\{\{\s*github\.(event\.(issue|comment|pull_request)\.(title|body)|head_ref)`,
			Target:      TargetContent,
		},
		{
			ID:          "CI-ABUSE-006",
			Title:       "Composite action shell with template injection",
			Description: "shell: bash/sh combined with ${{ in the same logical line context.",
			Category:    "ci-abuse",
			Mitre:       "T1195.002",
			Severity:    SeverityHigh,
			Pattern:     `(?i)shell:\s*(bash|sh).*\$\{\{`,
			Target:      TargetContent,
		},
		{
			ID:          "ENC-STEGO-001",
			Title:       "Base64 + XOR decode sequence",
			Description: "Detected decode sequence consistent with steganographic payload reconstruction.",
			Category:    "defense-evasion",
			Mitre:       "T1027.003",
			Severity:    SeverityHigh,
			Pattern:     `(?i)(base64.{0,40}xor|xor.{0,40}base64)`,
			Target:      TargetContent,
		},
		{
			ID:          "CI-SECRET-001",
			Title:       "CI environment variable dump marker",
			Description: "Detected full environment dump commands in CI context that can expose token material.",
			Category:    "ci-secret-hygiene",
			Mitre:       "T1552.001",
			Severity:    SeverityLow,
			Pattern:     `(?i)\b(printenv|env)\b.{0,120}(ACTIONS_|GITHUB_TOKEN|AWS_|AZURE_|GOOGLE_|CI_)`,
			Target:      TargetContent,
		},
		{
			ID:          "CI-SECRET-002",
			Title:       "Verbose shell tracing near secret context",
			Description: "Detected shell trace mode with likely secret-bearing variables, increasing accidental secret exposure risk.",
			Category:    "ci-secret-hygiene",
			Mitre:       "T1552.001",
			Severity:    SeverityLow,
			Pattern:     `(?i)\b(set\s+-x|bash\s+-x)\b`,
			Target:      TargetContent,
		},
		{
			ID:          "CI-SECRET-003",
			Title:       "Secret-bearing file upload marker",
			Description: "Detected upload/archive commands targeting files frequently containing credentials or environment secrets.",
			Category:    "ci-secret-hygiene",
			Mitre:       "T1567.001",
			Severity:    SeverityLow,
			Pattern:     `(?i)\b(curl|wget|aws\s+s3\s+cp|az\s+storage\s+blob\s+upload|gsutil\s+cp)\b.{0,220}(\.env|id_rsa|credentials|kubeconfig|config\.json)`,
			Target:      TargetContent,
		},
		{
			ID:          "CI-SECRET-004",
			Title:       "CI token persisted to workspace marker",
			Description: "Detected commands writing token-like variables to local files, increasing post-build credential residue risk.",
			Category:    "ci-secret-hygiene",
			Mitre:       "T1552.001",
			Severity:    SeverityLow,
			Pattern:     `(?i)(echo|printf).{0,120}\$(ACTIONS_RUNTIME_TOKEN|GITHUB_TOKEN|AWS_SESSION_TOKEN|AZURE_CLIENT_SECRET).{0,120}(>|>>)\s*[^|;&]+`,
			Target:      TargetContent,
		},

		// CI build script hygiene (CI-BUILD-001–009).
		{
			ID:          "CI-BUILD-001",
			Title:       "Container login with password on command line",
			Description: "docker login, podman login, or similar uses -p/--password flag, exposing credentials in process listing and shell history. Use --password-stdin instead.",
			Category:    "ci-build",
			Mitre:       "T1552.001",
			Severity:    SeverityCritical,
			Pattern:     `(?i)\b(docker|podman|buildah|nerdctl)\s+login\b.{0,120}(\s-p\s|--password[\s=])`,
			Target:      TargetContent,
			PathPattern: regexp.MustCompile(`(?i)(^|/)(build_deploy|pr_check|deploy|ci[_-]|Makefile|Jenkinsfile|\.gitlab-ci\.ya?ml|\.github/workflows/[^/]+\.ya?ml|\.circleci/|\.tekton/|Taskfile)|\.(sh|bash)$`),
		},
		{
			ID:          "CI-BUILD-002",
			Title:       "Docker build-arg passing secret variable",
			Description: "A --build-arg passes a variable with SECRET, TOKEN, PASSWORD, KEY, or CREDENTIAL in its name. Build args persist in image layer metadata and can be extracted from pushed images.",
			Category:    "ci-build",
			Mitre:       "T1552.001",
			Severity:    SeverityHigh,
			Pattern:     `(?i)--build-arg[= ]["']?\w*(SECRET|TOKEN|PASSWORD|KEY|CREDENTIAL)\w*[= ]`,
			Target:      TargetContent,
		},
		{
			ID:          "CI-BUILD-003",
			Title:       "Remote script execution in Dockerfile",
			Description: "curl or wget piped to bash/sh inside a Dockerfile RUN instruction. The fetched script content is not auditable and can change between builds.",
			Category:    "ci-build",
			Mitre:       "T1204.002",
			Severity:    SeverityCritical,
			Pattern:     `(?i)\b(curl|wget)\b.{0,200}\|\s*(bash|sh)\b`,
			Target:      TargetContent,
			PathPattern: regexp.MustCompile(`(?i)(^|/)Dockerfile`),
		},
		{
			ID:          "CI-BUILD-004",
			Title:       "Unconditional exit 0 in CI check script",
			Description: "A CI check script contains a bare 'exit 0' statement — if this is the only functional line, the CI gate provides no validation. Review whether the script performs actual checks before exiting.",
			Category:    "ci-build",
			Mitre:       "T1562.001",
			Severity:    SeverityMedium,
			Pattern:     `(?i)^\s*exit\s+0\s*$`,
			Target:      TargetContent,
			PathPattern: regexp.MustCompile(`(?i)(^|/)(pr_check|build_check|ci_check|check)\.(sh|bash)$`),
		},
		{
			ID:          "CI-BUILD-005",
			Title:       "Hardcoded stale Go toolchain in build script",
			Description: "Build script pins GOROOT or GOVERSION to an old Go release. Stale toolchains may contain known vulnerabilities.",
			Category:    "ci-build",
			Mitre:       "T1195.002",
			Severity:    SeverityMedium,
			Pattern:     `(?i)(GOROOT|GOVERSION)[= "]+.{0,20}go1\.(1[0-9]|20|21)\b`,
			Target:      TargetContent,
			PathPattern: regexp.MustCompile(`(?i)(^|/)(build_deploy|pr_check|deploy|Makefile).*$`),
		},
		{
			ID:          "CI-BUILD-006",
			Title:       "Environment variable dump in CI script",
			Description: "Full environment dump (env, printenv, set) in a CI script risks exposing injected secrets, tokens, and runtime credentials in logs.",
			Category:    "ci-build",
			Mitre:       "T1552.001",
			Severity:    SeverityHigh,
			Pattern:     `(?i)\bENV_DUMP\s*=\s*` + "`" + `\s*env\s*` + "`",
			Target:      TargetContent,
			PathPattern: regexp.MustCompile(`(?i)(^|/)(build_deploy|pr_check|deploy)\.(sh|bash)$`),
		},
		{
			ID:          "CI-BUILD-008",
			Title:       "Docker COPY/ADD full context without .dockerignore",
			Description: "Dockerfile uses COPY . . or ADD . . which copies the entire build context into the image layer. Without a .dockerignore, this includes .git/, .env files, secrets, and credentials.",
			Category:    "ci-build",
			Mitre:       "T1552.001",
			Severity:    SeverityHigh,
			Pattern:     `(?i)(COPY|ADD)\s+\.\s+\.`,
			Target:      TargetContent,
			PathPattern: regexp.MustCompile(`(?i)(^|/)(Dockerfile|Containerfile)`),
		},
		{
			ID:          "CI-BUILD-009",
			Title:       "Self-hosted GitHub Actions runner",
			Description: "Workflow uses self-hosted runners which have persistent state between jobs. Compromised workflows on self-hosted runners can leave backdoors, steal credentials, or pivot laterally.",
			Category:    "ci-build",
			Mitre:       "T1195.002",
			Severity:    SeverityMedium,
			Pattern:     `(?i)runs-on:\s*\[?\s*self-hosted`,
			Target:      TargetContent,
			PathPattern: regexp.MustCompile(`(?i)(^|/)\.github/workflows/[^/]+\.ya?ml$`),
		},

		// CI environment exposure (CI-ENV-001–008).
		{
			ID:             "CI-ENV-001",
			Title:          "Credential template file with non-placeholder values",
			Description:    "A .env.example or similar credential template file contains API_KEY, TOKEN, SECRET, or PASSWORD assignments with values that look like real credentials rather than placeholder text.",
			Category:       "ci-env",
			Mitre:          "T1552.001",
			Severity:       SeverityHigh,
			Pattern:        `(?i)(API_KEY|TOKEN|SECRET|PASSWORD|CLIENT_SECRET|JWT_SECRET)\s*=\s*\S+`,
			Target:         TargetContent,
			PathPattern:    regexp.MustCompile(`(?i)(^|/)\.env\.(example|sample|template|dev|local)$`),
			ExcludePattern: regexp.MustCompile(`(?i)=\s*(your[_-]|change[_-]?me|replace[_-]?me|xxx|TODO|CHANGEME|<[^>]+>|example|placeholder|insert[_-]|set[_-]?this|fill[_-]?in)`),
		},
		{
			ID:          "CI-ENV-002",
			Title:       "End-of-life runtime in CI service definition",
			Description: "CI workflow uses an end-of-life database or runtime version (e.g. postgres:11, node:14, python:3.6) as a service container. EOL software receives no security patches.",
			Category:    "ci-env",
			Mitre:       "T1195.002",
			Severity:    SeverityMedium,
			Pattern:     `(?i)\b(postgres|postgresql|mysql|mariadb|redis|mongo|node|python|ruby):(9|10|11|12|13|14|2\.7|3\.[0-6])\b`,
			Target:      TargetContent,
			PathPattern: regexp.MustCompile(`(?i)(^|/)\.github/workflows/[^/]+\.ya?ml$`),
		},
		{
			ID:             "CI-ENV-003",
			Title:          "Hardcoded credential in CI workflow env block",
			Description:    "A CI workflow YAML env block contains a hardcoded value for a variable whose name includes PASSWORD, SECRET, TOKEN, or KEY. Even 'dummy' credentials establish patterns attackers can exploit.",
			Category:       "ci-env",
			Mitre:          "T1552.001",
			Severity:       SeverityMedium,
			Pattern:        `(?i)(PASSWORD|SECRET_KEY|AUTH_TOKEN|DB_PASSWORD|CREDENTIAL):\s+[a-zA-Z0-9_.-]{4,}`,
			Target:         TargetContent,
			PathPattern:    regexp.MustCompile(`(?i)(^|/)\.github/workflows/[^/]+\.ya?ml$`),
			ExcludePattern: regexp.MustCompile(`(?i):\s*\$\{\{`),
		},
		{
			ID:          "CI-ENV-004",
			Title:       "Remote script sourced via process substitution",
			Description: "source <(curl ...) or eval $(curl ...) downloads and immediately executes a remote script. The content is not auditable and can change between runs.",
			Category:    "ci-env",
			Mitre:       "T1204.002",
			Severity:    SeverityHigh,
			Pattern:     `(?i)(source\s+<\(\s*(curl|wget)|eval\s+\$\(\s*(curl|wget))`,
			Target:      TargetContent,
		},
		{
			ID:          "CI-ENV-005",
			Title:       "CI secret with hardcoded fallback value",
			Description: "A GitHub Actions expression provides a literal fallback for a secret (secrets.X || 'value'). This means the workflow runs with a predictable value when the secret is unavailable, which can mask missing configuration or enable bypass.",
			Category:    "ci-env",
			Mitre:       "T1552.001",
			Severity:    SeverityMedium,
			Pattern:     `(?i)secrets\.\w+\s*\|\|\s*'[^']*'`,
			Target:      TargetContent,
			PathPattern: regexp.MustCompile(`(?i)(^|/)\.github/workflows/[^/]+\.ya?ml$`),
		},
		{
			ID:             "CI-ENV-006",
			Title:          "Hardcoded credential default in Helm values",
			Description:    "A Helm values.yaml defines a non-templated password, secret, or token default. These defaults often ship to production if not overridden.",
			Category:       "ci-env",
			Mitre:          "T1552.001",
			Severity:       SeverityHigh,
			Pattern:        `(?i)(password|secret|token|apiKey|api_key):\s*[a-zA-Z0-9_-]{3,}$`,
			Target:         TargetContent,
			PathPattern:    regexp.MustCompile(`(?i)(^|/)values\.ya?ml$`),
			ExcludePattern: regexp.MustCompile(`(?i)\{\{`),
		},
		{
			ID:          "CI-ENV-007",
			Title:       "Committed Terraform variables file",
			Description: "A terraform.tfvars file (not .example) is committed to the repository. These files often contain infrastructure identifiers, account IDs, and sometimes credentials that should not be in version control.",
			Category:    "ci-env",
			Mitre:       "T1552.001",
			Severity:    SeverityMedium,
			Pattern:     `(?i)(^|/)terraform\.tfvars$`,
			Target:      TargetPath,
		},
		{
			ID:          "CI-ENV-008",
			Title:       "Test private key file committed",
			Description: "A private key file is committed under a test directory. While test keys should not be production keys, committed private key material establishes patterns and may be accidentally reused.",
			Category:    "ci-env",
			Mitre:       "T1552.004",
			Severity:    SeverityLow,
			Pattern:     `(?i)(^|/)test.{0,30}(jwt_private_key|private_key|id_rsa|id_ed25519|key)\.pem$`,
			Target:      TargetPath,
		},

		// Shell eval risks (BHV-EVAL-001).
		{
			ID:          "BHV-EVAL-001",
			Title:       "Shell eval of dynamic content",
			Description: "Shell script uses eval with variable expansion or command substitution. If the expanded value is attacker-influenced, this enables arbitrary command execution.",
			Category:    "behavioral-signal",
			Mitre:       "T1059",
			Severity:    SeverityHigh,
			Pattern:     `(?i)\beval\s+["$\(]`,
			Target:      TargetContent,
			PathPattern: regexp.MustCompile(`(?i)\.(sh|bash|zsh)$|(^|/)(Makefile|Jenkinsfile)$`),
		},

		// Infrastructure policy (POL-TF-001, POL-ARGO-001).
		{
			ID:             "POL-TF-001",
			Title:          "Terraform S3 state backend without encryption",
			Description:    "Terraform backend configuration uses S3 without encrypt = true. State files contain resource attributes including secrets and should be encrypted at rest.",
			Category:       "infra-policy",
			Mitre:          "T1552.001",
			Severity:       SeverityMedium,
			Pattern:        `(?i)backend\s+"s3"\s*\{`,
			Target:         TargetContent,
			PathPattern:    regexp.MustCompile(`(?i)\.(tf|hcl)$`),
			ExcludePattern: regexp.MustCompile(`(?i)encrypt\s*=\s*true`),
		},
		{
			ID:             "POL-ARGO-001",
			Title:          "ArgoCD Application with automated prune",
			Description:    "An ArgoCD Application manifest enables automated sync with prune. A git push can delete cluster resources without approval, enabling destructive supply chain attacks.",
			Category:       "infra-policy",
			Mitre:          "T1485",
			Severity:       SeverityMedium,
			Pattern:        `(?i)prune:\s*true`,
			Target:         TargetContent,
			PathPattern:    regexp.MustCompile(`(?i)(^|/)(argo|argocd|app(lication)?s?)[/-].*\.ya?ml$`),
			ContextPattern: regexp.MustCompile(`(?i)(kind:\s*Application|apiVersion:\s*argoproj)`),
			ContextWindow:  15,
		},

		// Supply chain tooling (DEP-TOOL-001).
		{
			ID:          "DEP-TOOL-001",
			Title:       "Build-time tool install from mutable Go module ref",
			Description: "Makefile uses go install with @latest, @main, @master, or a branch ref. This resolves to whatever version is current at build time, enabling supply chain compromise if the upstream is taken over.",
			Category:    "supply-chain",
			Mitre:       "T1195.002",
			Severity:    SeverityMedium,
			Pattern:     `(?i)\bgo\s+install\s+\S+@(latest|main|master|HEAD)\b`,
			Target:      TargetContent,
			PathPattern: regexp.MustCompile(`(?i)(^|/)(Makefile|Taskfile)`),
		},

		// GitHub governance (CI-GOV-001–004).
		{
			ID:          "CI-GOV-001",
			Title:       "workflow_run chaining from untrusted trigger",
			Description: "workflow_run workflows inherit the triggering workflow's privileges. When the trigger is a PR from a fork, this can escalate untrusted code to write/secret scope.",
			Category:    "github-actions",
			Mitre:       "T1195.002",
			Severity:    SeverityHigh,
			Pattern:     `(?i)\bworkflow_run\b`,
			Target:      TargetContent,
			PathPattern: regexp.MustCompile(`(?i)(^|/)\.github/workflows/[^/]+\.ya?ml$`),
		},
		{
			ID:          "CI-GOV-002",
			Title:       "Auto-merge workflow without review gate",
			Description: "Workflow enables auto-merge or uses gh pr merge --auto without requiring review approval, bypassing human gate.",
			Category:    "github-actions",
			Mitre:       "T1195.002",
			Severity:    SeverityMedium,
			Pattern:     `(?i)(gh\s+pr\s+merge\s+.*--(auto|admin)|enable-auto-merge|auto-merge:\s*true)`,
			Target:      TargetContent,
		},
		{
			ID:          "CI-GOV-003",
			Title:       "CODEOWNERS with wildcard owner on sensitive path",
			Description: "A CODEOWNERS entry uses a wildcard (*) owner, which means any contributor can approve changes to the matched paths.",
			Category:    "github-actions",
			Mitre:       "T1195.002",
			Severity:    SeverityMedium,
			Pattern:     `^\s*\S+\s+\*\s*$`,
			Target:      TargetContent,
			PathPattern: regexp.MustCompile(`(?i)(^|/)CODEOWNERS$`),
		},
		{
			ID:          "CI-GOV-004",
			Title:       "gh pr merge --admin bypasses branch protection",
			Description: "Using --admin flag on gh pr merge bypasses branch protection rules including required reviews and status checks.",
			Category:    "github-actions",
			Mitre:       "T1195.002",
			Severity:    SeverityHigh,
			Pattern:     `(?i)gh\s+pr\s+merge\s+.*--admin`,
			Target:      TargetContent,
		},
	}
}
